### PR TITLE
Pricing

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/6jV1qOWJ

Pricing page, check the card for test details.
Abstract links:
- [staging desktop](https://share.goabstract.com/88ccf619-8564-4f12-987e-8e55e14caaac)
- [staging mobile](https://share.goabstract.com/19f8a973-91c5-44bf-ad69-a1dd62939e7e)
- [carrot.io desktop](https://share.goabstract.com/9755143e-2809-43f0-bb30-5f18bb3e9112)
- [carrot.io desktop email submitted](https://share.goabstract.com/4b7efda8-ca13-467b-8374-06a6a1538080)
- [carrot.io mobile](https://share.goabstract.com/19f8a973-91c5-44bf-ad69-a1dd62939e7e)

### CODE REVIEW

**Comment by bago2k4** [comment]
[Website - add pricing page; and link to help](https://trello.com/c/6jV1qOWJ/1203-website-add-pricing-page-and-link-to-help)

**Comment by belucid** [comment]
waiting for feedback from Ryan

**Comment by bago2k4** [comment]
We got the green light from our designer, moving this in ready for review

**Comment by thepug** [comment]
@bago2k4  Was google analytics needed to figure out that the collected email came from the pricing page and specifically which button? 

I think we want to keep track of this information.

**Comment by bago2k4** [comment]
@thepug good catch, let's talk about it tomorrow, should be very quick to add

**Pull request merged**
