### PR TITLE
Whats new dot

### PR DESCRIPTION
**Pull request by bago2k4**
#### NB: review after #849 

To test:
- open carrot
- wait a few seconds
- [x] do you NOT see a green dot besides your user avatar? Good
- add a new whats new item to headway
- refresh Carrot
- wait a few seconds
- [x] do you see a green dot besides the user menu? Good
- now open the menu
- [x] do you see a green dot besides what's new too? Good
- click Whats new
- [ ] do you see the headway widget in the right place? Good

NB: to make this work i removed the animation from the menu. Since that's almost always the first panel that opens i think it makes sense to remove all the panels animations at this point, WYT?

NB: this doesn't remove the page scroll when the menu (or probably another panel) appear, i won't fix it here though since that's fixed in #866

### CODE REVIEW

**Comment by belucid** [comment]
@bago2k4 seems the merge is still possibly bad? I don't get a clean app start in the browser on this branch at the moment (see Slack)

**Comment by belucid** [comment]
@bago2k4 after clicking through what's new and seeing the Headway widget, the numbering badge on the what's new in the menu goes away, but the green dot on the avatar in the header does not, it stays there until there is a page refresh.

**Comment by bago2k4** [comment]
@belucid in one of the feedback Ryan wanted the Whats new item to open a new tab pointing to https://whats-new.carrot.io/
If we do that though the badge count is not cleaned out, and i don't think i can force that since it's a cookie set on under that domain...
WYT?

**Comment by belucid** [comment]
@bago2k4 let's leave it as-is for now. We need the badge to clear out.

**Comment by bago2k4** [comment]
@belucid added a note in the description, repeating here to make sure: you shouldn't care if the page can't still scroll up and down when the menu (or another panel) is open, that will be fixed in #866

**Pull request merged**
