### PR TITLE
Small bug report

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/GSqkwDVK

To test follow the checklist in the card.
Also (at each step check the console for errors):
- try to load the company data
- change the company data
- refresh the page and check all data are there
- create a report
- refresh the report page and check all data are there
- update report data
- refresh the report page and check all data are there

### CODE REVIEW

**Comment by belucid** [comment]
Trying to create a new report gives a 404, resulting URL looks like:

http://localhost:3449/companiesOPEN/reports2015/M4/edit

**Comment by belucid** [comment]
Tab labels should be: Month Year

Ex: September 2015

Not: Period Year

**Comment by bago2k4** [comment]
@belucid should be good to go now

**Comment by bago2k4** [comment]
last commit also address this: https://github.com/open-company/open-company-web/pull/20#issuecomment-131366104

**Comment by belucid** [comment]
@bago2k4 please merge in mainline

**Comment by bago2k4** [comment]
@belucid ready

**Pull request merged**
