### PR TITLE
Show less jumps fix

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/yFOWlAZq

To test:
- add a long post
- expand the post
- focus on add comment
- click on Show less
- [x] does the post gets collapsed back? Good
- before it was only removing the focus to the add comment field causing a jump in the view, but no collapse

### CODE REVIEW

**Comment by bago2k4** [comment]
[Show less jump](https://trello.com/c/yFOWlAZq/1923-show-less-jump)

**Comment by belucid** [comment]
@bago2k4 If I type a comment in, then click "Show less", my comment is gone when I expand again via Show more or "Add a comment...". That's not good.

**Comment by bago2k4** [comment]
@belucid hmm y the comment is kept in the local component state, that is lost if you collapse the post.
This is unrelated to this though, i need a new PR to fix it.
Let me know if you add a trello card or want me to

**Comment by bago2k4** [comment]
@belucid added a new card for it

**Pull request merged**
