### PR TITLE
Company logo

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/Y62sBxoC

test:
- open a company page
- click on the logo (should bring you to the company profile page)
- insert an invalid url in the logo field (it should fail also if you load a valid url that is not an image: http://asd.com for example)
- unfocus the field, can you see an error message? good
- insert a valid image url in the logo field (https://buffer.com/images/app/buffer-logo@2x.png for example)
- unfocus the field
- does the company logo in the top left corner of the nav bar change? good
- remove the url
- unfocus the field
- does the logo go back to the letter logo? good
- merge

### CODE REVIEW

**Comment by belucid** [comment]
@bago2k4 

Updated values for the other items on the page besides logo (name, currency) aren't updated in the PATCH request when you update them.

**Comment by belucid** [comment]
@bago2k4 

If a company logo is provided it should completely replace the default in the top left of the nav. So there should be no round circle and we shouldn't have the company name in text. Just the provided logo.

**Comment by bago2k4** [comment]
@belucid should be good now

**Comment by belucid** [comment]
@bago2k4 please merge in mainline

Also make sure company name isn't in the header if we're using a custom logo.

**Comment by bago2k4** [comment]
@belucid done

**Comment by belucid** [comment]
@bago2k4 I see the company name when a custom logo is used:

http://take.ms/4uaql

**Comment by bago2k4** [comment]
@belucid i did that on purpose, in this case the logo already contains the company name but it won't be always the same, wyt? should i remove the name?

**Comment by bago2k4** [comment]
@belucid company name is shown only when there is no logo

**Pull request merged**
