### PR TITLE
Carrot 2.0

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/ISkq1g46

This is the first and (probably the only) giant PR for Carrot 2.0.

In this branch there is all the UI refresh done in the last few days plus the web side work of [this card](https://trello.com/c/tSMO0Qhf).

To test:
- [x] test the org settings panel
- [x] open org settings, stop storage, test org settings errors
- [x] test the integrations panel
- [x] test errors states for integrations (you should try faking the redirect back urls with access=false etc, let's discuss more if you need)
- [x] test the team management panel
- [x] test the team management panel errors (stopping auth service)
- [x] test the invites panel
- [x] test the invites panel errors (stopping auth service)
- [x] test user settings panel
- [x] test user settings panel errors (stop auth service)
- [x] test user notifications panel
- [x] test user notifications panel errors (stop auth service)
- [x] test reminders panel
- [x] test reminders panel errors (stop reminders service)
- [x] test All Posts: load more items, more menus, reactions
- [x] test section: scroll items, more menus, reactions
- [x] test section settings panel
- [x] test section settings panel errors (stop storage service)
- [x] test navigation sidebar
- [x] test the expanded post view: post with only text, with images, with videos, with attachments (1 or more)
- [x] test comments: add, edit, delete

Test read send:
- [x] Not when there is truncated body
- [x] Not when body contains at least one image
- [x] Not when body contains at least one video (Youtube or Vimeo)
- [x] Not when body contains a recorded (Ziggeo) video
- [x] Not when post has comments
- [x] Not when post has attachments
- [x] Yes when body is not truncated and all the above are not met

### CODE REVIEW

**Comment by bago2k4** [comment]
@belucid before you merge this i need to clean up a bit the components that are not used anymore and also fix tests

**Comment by bago2k4** [comment]
[White background for unread posts](https://trello.com/c/tSMO0Qhf/1985-white-background-for-unread-posts)

**Comment by belucid** [comment]
@bago2k4 please merge mainline into this. There are some conflicts.

**Comment by belucid** [comment]
@bago2k4 big bloated icon on FF for notifications: https://take.ms/swltY

**Comment by belucid** [comment]
@bago2k4 info tooltip on "Allowed email domains" in org panel w/ copy of: "Any user that signs up with an allowed email domain and verifies their email address will have contributor access to your team."

**Comment by belucid** [comment]
@bago2k4 this shouldn't be here, we don't have this feature: https://take.ms/MOdiL

**Comment by belucid** [comment]
@bago2k4 after completing "Add to Slack" I end up back at "Admin settings" rather than at "Integrations" panel.

**Comment by belucid** [comment]
@bago2k4 UI is all goofed up here: https://take.ms/19K2p

**Comment by belucid** [comment]
@bago2k4 text in these green buttons is too low (not vertically centered) on FF: https://take.ms/2afKl

**Comment by belucid** [comment]
In the dialogs moved to panels, we no longer show the unsaved changes confirmation dialog. E.g. https://files.slack.com/files-pri/T06SBMH60-FJ4664ZQR/image.png

**Comment by bago2k4** [comment]
@belucid this should be good again.

Feedback fixes:

- FF bell icon bloated: is see it ok, i saw that too on Chrome, try refreshing (cache maybe)
- allowed email domains info: added
- slack joining user type selector: commented out
- land on org settings adding Slack: now add team/org redirect to integrations
- team management goofed UI: fixed
- Save/Invite buttons are not vertically centred: fixed
- lose change dialog: added to org settings and invite (the other panels had it or didn't need it)

**Comment by belucid** [comment]
@bago2k4 I've got the Carrot bot on, but the "Invite via" dropdown in the invite panel only has email as an option.

**Comment by belucid** [comment]
@bago2k4 I had just myself listed in manage team. I invited 1 user. Still had just myself. Refreshed the page, now I have no one: https://take.ms/MjCSa

**Comment by belucid** [comment]
@bago2k4 

Left nav. spacing is messed up for a viewer:

https://take.ms/1THKp

When compared to a contributor:

https://take.ms/91NLv

Presumably due to not having "Drafts".

**Comment by belucid** [comment]
@bago2k4 empty section placeholder for viewers is ne bona: https://take.ms/MbvBV

**Comment by belucid** [comment]
> @bago2k4 empty section placeholder for viewers is ne bona: https://take.ms/MbvBV

For now, let's change the "Create a post to get started" copy to, "There's nothing to see here"

**Comment by bago2k4** [comment]
@belucid issues have been fixed, moving this back in ready for review

**Comment by bago2k4** [comment]
@belucid new commits you see are to fix the feedback from here https://trello.com/c/s9GcKqFv/1987-carrot-20-feedback
And also to fix a bug @cjsauer found and that we discussed in Slack: if you loaded the post view directly the posts were shown in reverse order since they were displayed in the same order storage branch was returning it (the comments loaded from the section/ap api, no the IS api).
For this bug i have added also a backlog card with some improvements he suggested https://trello.com/c/pnEJ9FML/195-comments-sorting-improvements

**Comment by bago2k4** [comment]
@belucid feedback fixed

**Comment by belucid** [comment]
@bago2k4 open notification settings from the dropdown, make some changes, save it, close it with the X. The admin settings panel opens. Should be nothing open.

**Comment by belucid** [comment]
@bago2k4 I have all my notifications right now to "Via email". I go and set them all to "Via Slack", then hit save. The HTTP request has "Via Email", for all 3 and they go back to "Via Email" in the UI.

**Comment by belucid** [comment]
@bago2k4 open recurring updates, close it with the X, try to open the dropdown dialog again... you can't (and in fact the rest of the app is non-responsive too).

**Comment by belucid** [comment]
@bago2k4 must see button when toggled in bmail is borked: https://take.ms/RYlGu

**Pull request merged**
