### PR TITLE
Marketing site

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/dYkM5Yby/818-marketing-site

Port the ML design of the marketing site to our site and blog.

To test:
- navigate our marketing site starting from the home page and using internal navigation
- navigate our marketing site starting from the home page and using internal navigation with an iPhone (or enter device mode in chrome debug tools and select an iPhone model)
- navigate our marketing site starting from the home page and using internal navigation with an iPad (or enter device mode in chrome debug tools and select an iPad model)
- navigate to /about and /features and make sure they looks the same as you are coming from the homepage
- check the above from iphone and ipad
- navigate to blog
- check that the blog links are pointing where they should, they point to our production server so clicking will give you errors
- check the blog from iPhone and iPad
- check the blog post page with all 3 window sizes
- merge
- dance
- turn around and kiss your ferret (hope you removed the glands 🤣 )

This also fixes the fonts that were missing here https://github.com/open-company/open-company-web/pull/244#issuecomment-308690339

### CODE REVIEW

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@bago2k4 

Big Web

- [ ] The middle and bottom button should also say "Get Early Access" not Get Started.
- [ ] Only the button should be there until you click it, then the email address should appear.
- [ ] I don't get any illustration images on the Features page (localhost or on staging) https://monosnap.com/file/ONSs4HDvsAgxfSLl8smYeMKbsWOLCJ.png
- [ ] Request Free Early Access link in Footer below Carrot doesn't seem to actually do anything
- [ ] Clicking Get Early Access button top right doesn't actually do anything
- [ ] Close the big gap on the About page http://take.ms/g5Xyn
- [ ] Our team is goofed up on About with an extra You?
 box https://monosnap.com/file/wXv5xORzlAEDX8hcKrEGjbinBVzxud.png
- [ ] Put Iacopo bottom left and You? bottom right in About
- [ ] Say hello button doesn't actually do anything

Mobile:

- [ ] Stuart: I don't see a Thanks! message, I just lose the space where I typed in my name... as it goes to the top, then I see the first image
- [ ] Stuart: Make the headline smaller on mobile so it takes up less space

**Comment by bago2k4** [comment]
@belucid this is good again for review

**Comment by bago2k4** [comment]
@belucid all the feedback issues should be addressed now

**Pull request closed without merging**
