### PR TITLE
Mobile share

### PR DESCRIPTION
**Pull request by bago2k4**
### Review after #336 

Card: https://trello.com/c/nKpWC0GP

To test on your mobile device:
- setup an org with slack
- make sure it has the bot
- load a board
- tap the vertical ellipsis
- tap on Share
- [x] share via slack
- [x] share via url (check the copy button actually copy the url)
- [x] share via email

### CODE REVIEW

**Comment by belucid** [comment]
@bago2k4 

- [ ] the landing page for the share URL is not mobile ready yet

**Comment by belucid** [comment]
@bago2k4 

- [ ] can we put metadata on the email field in the share dialog so we get the email keyboard treatment? Right now we get the keyboard w/ no `@` symbol and it wants to auto-upper case the first letter.

**Comment by bago2k4** [comment]
@belucid i have changed the input type to be email so the mobile keyboard used is the right one. About the shared URL i think we should do a new PR for that, we can wait on this to merge or deploy but i won't do it here.
Do you know if a design exists? I can try guessing the best mobile layout with what we have and let Ryan react it. WYT?

**Comment by bago2k4** [comment]
@belucid just pushed a new bug fix: if you share from a post view you don't see the share view until you dismiss the post view. Check also that it didn't regress on desktop because it touches that code too.

**Pull request merged**
