### PR TITLE
Dev charts

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/KeTPkIyd

to test:
- start the app
- check the pie chart in headcount and compensation
- if you modify some data in headcount or compensation the pie chart should update live

### CODE REVIEW

**Comment by belucid** [comment]
Add currency symbol and thousand (and million) delimiter to compensation pie chart toolips:

http://stackoverflow.com/questions/13650191/google-chart-number-formatting

**Comment by belucid** [comment]
Add thousand delimiter to headcount pie chart tooltip. (or only show %)

**Comment by belucid** [comment]
Headcount labels get truncated:

Full-time emplo...

Show the full label.

**Comment by bago2k4** [comment]
@belucid should be good to go

**Pull request merged**
