### PR TITLE
New bw dashboard

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/yNFcmJAT

Add the topics list on Desktop layout. Use 3 and 2 columns layout for Desktop and tablets but only the first get the ToC on the left. Also review the calculations of the columns width trying to use the most available space.
Also add some style changes like removing the company avatar from the Dashboard and the Updates and Create Update page (but not from the shared update page).
Fix some small alignment issues with the navbar and the footer.

### CODE REVIEW

**Comment by bago2k4** [comment]
[Left-side Topic List with DnD, Remove “pinning"](https://trello.com/c/yNFcmJAT/730-left-side-topic-list-with-dnd-remove-pinning)

**Comment by belucid** [comment]
@bago2k4 

- [ ] Remove all the onboarding tips for now since they are out of date
- [ ] Hide the whole nav. bar when they have no topic
- [ ] Show the whole nav. bar (Dashboard/Updates/Share new update) when they have a topic

**Comment by bago2k4** [comment]
@belucid ready again.

**Comment by belucid** [comment]
@bago2k4 

Accessing public company w/ R/O permissions:

- [ ] No nav. even though there are updates
- [ ] Ellipse menu doesn't work
- [ ] Can attempt a DnD, shouldn't be able to

**Pull request merged**
