### PR TITLE
Fix shaky again

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/susDKdVV

Digest url: /11-october-5/all-posts?at=2018-10-12T13:13:07.432Z
the at parameter is the published-at of the post

To test:
- check locally with a digest URL of the company for whom you are logged in
- [x] do you see the post? Good
- use the same url but change the timestamp to be fake (ie: not found)
- [x] do you see the post removed screen? Good
- check locally with a digest URL of another org
- [x] do you see the post removed wall? Good
- now logout
- check a digest URL (not a public section)
- [x] do you see the login wall? Good
- try to login using one of the 3 methods
- [x] did it work? Good
- deploy and check the same on staging (timing of the resource load is different, that may affect the check even if it shouldn't)

TODO: remember the URL and redirect there after login, right now it's not a quick thing, added a backlog card for it

### CODE REVIEW

**Comment by bago2k4** [comment]
[Logged out user clicking digest link](https://trello.com/c/susDKdVV/1554-logged-out-user-clicking-digest-link)

**Comment by thepug** [comment]
@bago2k4 I get a 404 here.  Not sure what this means.
>  do you see the login wall? Good

**Comment by bago2k4** [comment]
@thepug were you testing on staging? can you provide a bit more details like the URL you visited, if the company was public or if you were looking at a post inside a public section?

**Comment by bago2k4** [comment]
@thepug fixed the issue you found. Also i have added test steps for 404s here https://docs.google.com/document/d/1tXjtvZecqAI4onH5W6GL6UC0dGUtcmfQyo7CANWy-Nc/edit#heading=h.wydiy3s3zp8s

**Pull request merged**
