### PR TITLE
Everything foc

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/Fm3cuWp4

### CODE REVIEW

**Comment by belucid** [comment]
@bago2k4 

- [ ] under 1057px viewport width, but while still 3 columns, save and cancel stack: https://files.slack.com/files-pri/T06SBMH60-F1YJUKND9/screen_shot_2016-08-05_at_10.56.40_am.png
- [ ] Don't show archive icon in newly added topic (when cancel will undo the PATCH)

**Comment by belucid** [comment]
@bago2k4 

- [ ] Emoji icon visible when add URL UI is showing: https://files.slack.com/files-pri/T06SBMH60-F1YLT4DHD/screen_shot_2016-08-05_at_11.20.32_am.png
- [ ]  if you have a new topic… haven’t saved yet… but you have an image and you hover on the camera, the black tooltip says Add an image, but there’s another gray tooltip below that says Replace the image.

**Comment by belucid** [comment]
@bago2k4 

- [ ] lost the tooltip after creation of 1st topic for a new company (probably lost w/ add topic changes)

**Comment by bago2k4** [comment]
@belucid 
> Emoji icon visible when add URL UI is showing: https://files.slack.com/files-pri/T06SBMH60-F1YLT4DHD/screen_shot_2016-08-05_at_11.20.32_am.png
this problem is present only in the staging-testing branch, this branch and the emojione-picker don't have it, it was caused by a wrong resolved conflict. We need to remember this when we merge these PRs. Good catch

**Comment by bago2k4** [comment]
@belucid 
>  if you have a new topic… haven’t saved yet… but you have an image and you hover on the camera, the black tooltip says Add an image, but there’s another gray tooltip below that says Replace the image.
Bootstrap doesn't like much to change the tooltips once they are initialised, that's why you see the original tooltip in the bootstrap bubble and the new one in the browser default tooltip.
Can't we use something like `Add/replace image` instead?
I can do this but i don't like add all that js only for a tooltip.

**Comment by belucid** [comment]
@bago2k4 please merge in mainline

**Comment by belucid** [comment]
@bago2k4 

- [ ] at <= 1046px (but still > 2 col) the pencil icon is pushed down creating a big gap between title and headline

**Comment by bago2k4** [comment]
@belucid ready!

**Pull request merged**
