### PR TITLE
Front of Card Editing

### PR DESCRIPTION
**Pull request by bago2k4**
https://trello.com/c/KiX8PWGH

### CODE REVIEW

**Comment by belucid** [comment]
@bago2k4 

- [ ] Errors out on staging
- [ ] Pencil can be hard to see on a dark image. Let's put the pencil below the image in the same spot it'd be in a card w/ no image: http://take.ms/xlYa9

**Comment by belucid** [comment]
@bago2k4 please merge mainline

**Comment by belucid** [comment]
@bago2k4 

- [ ] pull
- [ ] merge mainline
- [ ] Camera and plus should be on the left, only archive on the right http://take.ms/hI2Ef
- [ ] Sequence: FoC Edit, make some changes, click the add more content plus button, your edits are there, but save is not yet active until you make additional edits, it should be active immediately since you have pending edits.
- [ ] Pencil can be hard to see on a dark image. Let's put the pencil below the image in the same spot it'd be in a card w/ no image: http://take.ms/xlYa9

**Comment by belucid** [comment]
- [ ] FoC image offset in expanded card view http://take.ms/op56q

**Comment by belucid** [comment]
@bago2k4 

- [ ] FoC image offset in expanded card view http://take.ms/op56q
- [ ] Unstyled link in FoC snippet in expanded card view http://take.ms/JvJjt

**Comment by belucid** [comment]
@bago2k4 

- [ ] weird link behavior in body in expanded card view: http://take.ms/DOEau http://take.ms/MdDot
- [ ] clicking add topic just 404s

**Comment by belucid** [comment]
@bago2k4 

**Code**
- [ ] pull
- [ ] merge mainline

**FoC**

- [ ] Camera and plus should be on the left, only archive on the right http://take.ms/hI2Ef
- [ ] missing line divider above save / cancel buttons
- [ ] Pencil can be hard to see on a dark image. Let's put the pencil below the image in the same spot it'd be in a card w/ no image: http://take.ms/xlYa9 Position the same for finance and growth for 
- [ ] X to delete image should be white X in a #4E5A6B circle, so it shows up clearly on any kind of image
- [ ] Adding an image shouldn't go straight to the file u/l dialog, but should instead go to the same 2 options as back of card editing: "Select an image" or "provide an image URL"

**Expanded Card**

- [ ] make expanded card snippet and body text #4E5A6B, use the lighter grey color we have right now only for placeholder text
- [ ] Sequence: FoC Edit, make some changes, click the add more content plus button, your edits are there, but save is not yet active until you make additional edits, it should be active immediately since you have pending edits.
consistency
- [ ] FoC image is offset in expanded card view http://take.ms/op56q
- [ ] Unstyled link in FoC snippet in expanded card view http://take.ms/JvJjt
- [ ] weird link appearance and hover behavior in body in expanded card view: http://take.ms/DOEau http://take.ms/MdDot
- [ ] Extra "10" counter always in expanded card http://take.ms/YA3sW
- [ ] Missing the "ADD MORE BELOW" label and body placeholder text “Anything else to add? You can add more text and images here.”
- [ ] If user clicks pencil from expanded card, heading is the active field, this is good, if however the user clicks the + from front of card editing, let's make the body field the active field instead
- [ ] Since for now, the only thing the expanded card (+) does is add images, let's use the camera icon rather than the (+) icon, use the (X) still to close it, though you won't be able to animate the camera into the X like we did with the (+)

**Comment by belucid** [comment]
@bago2k4 

- [ ] Add Topic button wording is very faint on this branch.

**Comment by belucid** [comment]
@bago2k4 

**FoC**

- [ ] Don't show the archive topic button on the FoCE immediately after an add topic (ultimately they'll Cancel instead)
- [ ] Replace + icon with this icon: http://fontawesome.io/icon/expand/ and make tooltip always "Expanded view"
- [ ] Leave camera icon after photo has been used, just change the tooltip to "Replace image". If they use the camera, replace the image
- [ ] For consistency of weight, let's use FA's pencil http://fontawesome.io/icon/pencil/
- [ ] READ MORE is indented on the iPad (see Stuart's image in #general)

**Expanded View**

- [ ] Put same size pencil in the same spot as FoC (in the card), rather than top right
- [ ] Move buttons (back to dashboard, archive, save, cancel) into alignment with the edges of the card/body http://take.ms/ff42v
- [ ] Camera should still be there in the "card" portion to add/edit that image

**Comment by belucid** [comment]
@bago2k4 


 - [ ] Buffer on staging (and presumably anywhere you import it) then go to team and hiring expanded, then nav. back later a few times. On the 3rd nav. back you get just blank page.

**Comment by belucid** [comment]
**FoC**

- [ ] Headline prompt text should stay in place until user types
- [ ] Snippet prompt text should stay in place until user types
- [ ] Rather than the camera exposing the 2 image links, let’s have 2 icons, the camera with “Upload an image” as tooltip, and http://fontawesome.io/icon/code/ with “Provide an image link” as tooltip. 
- [ ] Placeholder text cut off for Diversity: http://take.ms/281RA
- [ ] After editing, then save, card goes back to old state (old content, or placeholder content), then updates after a delay. This isn’t an ideal feel, user has a panic moment and it doesn’t feel as polished.

**Expanded View**
- [ ] Body prompt text should stay in place until user types
- [ ] (+) is off by 1 line from the cursor http://take.ms/57tPF
- [ ] Rather than the (+) exposing the 2 image links, let’s have 2 icons, the camera with “Upload an image” as tooltip, and http://fontawesome.io/icon/code/ with “Provide an image link” as tooltip.
- [ ] Swap the positioning of the camera and the char counter so camera feels like it’s in the same position as on FoC
- [ ] Sequence: add a topic, then expand, then back to dashboard w/o editing. Card should still be open and waiting for editing, like after the add
- [ ] Consistent snippet placeholder text styling w/ FoC

**Technical**
- [ ] Add topic dialog doesn’t close after add (despite no JS console error) on staging Buffer
- [ ] 422 PATCHing Stuart’s `front-office-collections-etc` company on new topic add on staging
- [ ] Ended up w/ multiple fundraising PATCHed in when Stuart and I were editing at the same time, check for duplicate topic name in both client and server

**Comment by belucid** [comment]
@bago2k4 

A couple more design tweaks.

- [ ] Make the page background in expanded view white, not grey
- [ ] Change the body label in expanded view editing (yet again), this time to "ADDITIONAL INFORMATION"

**Comment by belucid** [comment]
@bago2k4 

**FoC**

- [ ] Remove archive

**Expanded**

- [ ] align buttons to "card" edge rather than text edge
- [ ] the colors of buttons got darker, not sure that was desired
- [ ] it’s a bit odd w/ save coming and going (edited), better to have it always there, but disabled

**Comment by belucid** [comment]
@bago2k4 

**Growth**

- [ ] + NEW METRIC shouldn't be shown while the metric adding UI is up (such as just after adding the growth topic for the first time
- [ ] Adding initial metric is broken, after clicking add, there is sadness
- [ ] Adding additional metric, after clicking add, the new metric isn't the selected metric for editing, it should be

**Comment by belucid** [comment]
@bago2k4 

- [ ] adjust button alignment http://take.ms/1ilIS

**Comment by belucid** [comment]
- [ ] Can’t edit the headline on /message-io in Team and Hiring. Try deleting “An offer for” and leaving the rest. Save. The PATCH request contains the original headline. Won’t stick.
- [ ] Resize /message-io on staging from three columns to two columns, and Team and Hiring topic disappears

**Comment by bago2k4** [comment]
@belucid about this:
> Copied text from an email into snippet. It was over the size limit. Shouldn't have allowed the save but it did. Same for other limited fields, title and headline.

The problem is caused by the `div[contentEditable]`, it doesn't support max-length like an `input[type=text]` does. What i'm doing now is intercepting the keyup and keydown event in the field, calculate the length and block the action (ie: adding a new letter) if the size exceeds the length. The problem with this approach is that I block the key press action only if the key pressed was a letter or a number, i can't block each key press or the user won't be able to delete text or move around in the field with the arrows if the text exceeds the length. Pasting in something goes with it.
I could cut the text to the preferred length but it's not a simple thing to achive since these elements have html tags in it so i could end up with a broken html DOM.

I added a comment to this discussion on medium editor to see if anyone has a better solution: https://github.com/yabwe/medium-editor/issues/962

NB: pasting something in the title field should automatically cut at the desired length

**Comment by belucid** [comment]
**Expanded**

- [ ] Sequence: expand, edit, make a change in body, click cancel, click edit again, change is there again, shouldn't be

**Growth**

- [ ] + NEW METRIC shouldn't be shown while the metric adding UI is up (such as just after adding the growth topic for the first time) http://take.ms/0GsOQ
- [ ] Adding initial metric is broken, after clicking add, there is sadness. Seems there is a 500 response, but I don't see any Sentry error from staging API
- [ ] Adding additional metric, after clicking add, the new metric isn't the selected metric for editing, it should be

**Comment by bago2k4** [comment]
@belucid 
> Ended up w/ multiple fundraising PATCHed in when Stuart and I were editing at the same time, check for duplicate topic name in both client and server

I quickly checked but i couldn't find anything to go deeper on this. if you can provide more details i can give it another shot.

**Comment by belucid** [comment]
- [ ] Sequence: Buffer, archive a topic, then add a topic and select the just archived topic, it opens in FoCE, click save. You get a blank topic: http://take.ms/CuFzv (Everything is as expected though after a refresh)
- [ ] Adjust button alignment: http://take.ms/oDMK7
- [ ] Align image icons w/ text: http://take.ms/Yxyzg
- [ ] Yellow line not flush w/ bottom on a short update and a long screen http://take.ms/kzray

**Comment by belucid** [comment]
@bago2k4 

- [ ] Sequence: Buffer, archive a topic, then add a topic and select the just archived topic, it opens in FoCE, click save. You get a blank topic: http://take.ms/CuFzv (Everything is as expected though after a refresh)
- [ ] Adjust button alignment: http://take.ms/oDMK7
- [ ] Align image icons w/ text: http://take.ms/Yxyzg
- [ ] Yellow line not flush w/ bottom on a short update and a long screen http://take.ms/kzray

**Comment by bago2k4** [comment]
@belucid can't replicate the blank topic thing. i tried with 2 topics: product and values. After clicking save both were not blank, the expected content was there, before and after refresh

**Comment by belucid** [comment]
@bago2k4 works for me now too. Not sure why. Oh well!

**Comment by belucid** [comment]
This one is ready to go. Waiting on your review of the API PR @bago2k4

**Pull request merged**
