### PR TITLE
Inline media picker

### PR DESCRIPTION
**Pull request by bago2k4**
#### Review after #853 

Card: https://trello.com/c/PWmoWtjU

To test:
- open Cmail
- type some text
- [x] do you get the inline picker when the new line is empty?
- [x] can you add an image?
- [x] can you add a YouTube video?
- [x] can you add a Vimeo video?
- [x] can you add a Loom video?
- [ ] can you add a live recorded video with Ziggeo?
- [ ] no trouble when the Ziggeo recording ends, for example the inline media pickler is still shown after you added the video?
- [x] can you add an attachment to the post?
- [x] can you insert emojis in all fields?
- [x] can you delete the draft/post with the trash can?
- now switch to fullscreen
- [ ] make sure you can complete all the steps above
- [x] finally try to publish a post
- [x] try to edit a published post

### CODE REVIEW

**Comment by bago2k4** [comment]
[Inline media editor](https://trello.com/c/PWmoWtjU/2009-inline-media-editor)

**Comment by belucid** [comment]
@bago2k4 please resolve the conflicts here.

**Comment by belucid** [comment]
@bago2k4 can't record a Zig video on this branch. After allowing camera access nothing happens.

**Comment by bago2k4** [comment]
@belucid i tried on Chrome and FF, when i click the `Record a video` button i see a big black square appearing at the top, do you see it?
With that also i see the permissions dialog, when i grant permissions i see my video in the black square and i can record.
Do you see something like this? Maybe if you record a quick loom?

Also check if you have any error in the console related to the media resources, i remember FF having errors because it didn't want to enable video access on not secure sources (no https).
Maybe i changed something in the browser configuration to make that work.

**Comment by belucid** [comment]
@bago2k4 y, I think it's a no HTTPS thing in FF. Works on staging. Moving on.

**Comment by belucid** [comment]
@bago2k4 seems we've got an issue now with Zig videos and us going to the full page screen after posting. Here's the sequence:

- Create a new post
- Add a headline, abstract and Zig video
- Post it
- You're returned to the full page of the posted post, with the "Preparing video" grey box where the video is
- Then the grey box is replaced with a black box. But you never see your video there, you have to leave the full screen post and come open it again to see it.

**Comment by belucid** [comment]
@bago2k4 Just remove the create a new Zig functionality from the UI for Carrot 2 (leave the display a Zig functionality in place for now).

**Pull request merged**
