### PR TITLE
Archived topics

### PR DESCRIPTION
**Pull request by bago2k4**
card: card: https://trello.com/c/P9pykwGj

#### Please merge after #124 or merge only this after reviewing both

To test:
- archive a topic
- check the add topic popover to see if it appears in the archived topics section
- archive some more topics
- check the order of the topics: they should be in alphabetical order
- add back a topic: you should see the topic with the old content
- merge

### CODE REVIEW

**Comment by belucid** [comment]
@bago2k4 please merge in `snapshot-revised-flow`

**Comment by belucid** [comment]
- [ ] Don't show the "ARCHIVED TOPICS" header if there aren't any yet

**Comment by belucid** [comment]
@bago2k4 once the above is complete, you can merge this into `snapshot-revised-flow` PR and close this one.

**Comment by belucid** [comment]
:+1: Looks good other than the 1 above issue.

**Comment by bago2k4** [comment]
Merged this in #124. Closing this PR to not merge 2 times the same branch in mainline.

**Pull request closed without merging**
