### PR TITLE
New dashboard

### PR DESCRIPTION
**Pull request by bago2k4**
cards:
- https://trello.com/c/1j9Tx2M4
- https://trello.com/c/mlJuFBg7
- https://trello.com/c/QPLHeb1C

Placeholder to collect feedback

### CODE REVIEW

**Comment by belucid** [comment]
- [ ] Clicking in the chart section of a data topic card should open the card, it doesn't
- [ ] Footer isn't fixed in place like the header, but should stick to the bottom of the view in the case of a window taller than needed (the grey BG should take up the extra space) http://take.ms/ZcwRy

**Comment by belucid** [comment]
@bago2k4 merge mainline

**Comment by belucid** [comment]
Both
- [ ] Company name should be vertically centered on icon, it's a bit low now

Desktop Web
- [ ] Adjust the background color transparency from 0.9 to 0.96 for expanded cards
- [ ] In the white pre-footer powered by section, the height above the first content is 54, in implementation padding is 90. Reduce to 54 above/below.
- [ ] Move the close X just outside the scroll area and make it fixed so the X stays in place as the content scrolls http://take.ms/jrtCc

Mobile Web
- [ ] Avatar should be hamburger menu (also note, on a real iPhone, avatar is currently cut in half)
- [ ] Expanded card has no transparency on mobile
- [ ] Left and right of card (grey) margin is just 9px on mobile per Zeplin
- [ ] Intercard Gap is just 12px on mobile per Zeplin
- [ ] Image pulls to front of card are distorted (see Pablo and Diversity)
- [ ] Remove OC logo from footer on mobile, should be About, Contact, Twitter and GH on 1 line
- [ ] Circles on charts have graph poking through like what used to happen on desktop

**Comment by bago2k4** [comment]
@belucid this should be good again

**Comment by belucid** [comment]
Both

- [ ] If user taps or clicks pillbox on front of data topic card just switch displayed metric and don't expand the card. Tapping/Clicking anywhere else on front of data card should expand.

Mobile

- [ ] Don't need gold line at the bottom of expanded card

**Comment by bago2k4** [comment]
@belucid _11. Dashboard - web v2 - card_ has the yellow line at the bottom of the expanded card, i guess the difference is that i have a fixed yellow line that is always visible at the bottom of the expanded card, in the design it's visible only when you scroll all the way down

**Comment by belucid** [comment]
@bago2k4 it's just a change from the mock. Stuart doesn't like the yellow at the bottom of expanded topic, fixed or not.

**Comment by bago2k4** [comment]
@belucid should be good again

**Comment by belucid** [comment]
@bago2k4 merge mainline

**Comment by bago2k4** [comment]
@belucid done

**Comment by belucid** [comment]
@bago2k4 merge mainline

**Comment by belucid** [comment]
@bago2k4 please merge in add/remove/edit here and use this as the 1 new design branch.

**Comment by belucid** [comment]
Going to collect editing feedback here as this is the open PR for the new design work

- [ ] https://app.getsentry.com/opencompany/oc-staging-web/issues/128826334/

**Comment by bago2k4** [comment]
closing this PR and opening a new one that contains these and some more of the latest work from me, martin and sean. the sentry error linked above was a one time error, probably a caching problem or something like that. ignoring for now, it will pop up again if it's a real issue.

**Pull request closed without merging**
