### PR TITLE
Share Snapshot Via Email

### PR DESCRIPTION
**Pull request by martinklepsch**
[trello card](https://trello.com/c/4dHNx5oa/503-share-snapshot-via-email-ui)

**To Test**

- [ ] Create a snapshot
- [ ] Press Share via Email
- [ ] Enter To, Subject & Note
- [ ] Verify that there's some validation on the *To* field
- [ ] Submit

Notable:

- All modals now have the same width. We can can customize this if we want it back, I mostly
  wanted to simplify the positioning code for now. Could probably still be improved further (flexbox).
- Updates to Clojure 1.9.0-alpha8

### CODE REVIEW

**Comment by belucid** [comment]
@martinklepsch please merge mainline

**Comment by martinklepsch** [comment]
@belucid updated

**Comment by belucid** [comment]
@martinklepsch 

- [ ] pull
- [ ] "Open in New Window" link in share URL isn't styled properly (see current on mainline/beta)
- [ ] Dialog title text isn't the right color
- [ ] Share to Slack dialog has link icon rather than Slack icon
- [ ] Divider line below dialog title is too dark, not the right color
- [ ] Zeplin has "dialog title" area above the divider line as 76px. It's too tall.
- [ ] Zeplin has 38px between your message text box and cancel/send. Too much white space.
- [ ] Your message text box should be twice as tall (120px, 4 lines worth) on Slack and Email

**Comment by belucid** [comment]
@martinklepsch please merge mainline

**Comment by martinklepsch** [comment]
> Zeplin has "dialog title" area above the divider line as 76px. It's too tall.

I used the same padding for the dialog title as for the rest of the dialog which felt consistent and visually balanced to me. Updated it now so that y-axis paddings are a bit smaller on the dialog title.

**ready again**

**Pull request merged**
