### PR TITLE
UX desktop: comments count fix

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/OzDxeUwY

To test:
- add a comment
- add another
- now delete one
- [x] comments count at the top of the comments is right? Good

Regression test (we saw in #256 ):
- go to the post view (copy url from share)
- add comment
- add another
- delete a comment
- go back to AP
- [x] comments count is right? Good

### CODE REVIEW

**Comment by bago2k4** [comment]
[UX desktop: comments count](https://trello.com/c/OzDxeUwY/1883-ux-desktop-comments-count)

**Comment by belucid** [comment]
@bago2k4 the comment count is now accurate for deletes, but the facepile isn't. It keeps the avatar of deleted comments.

**Comment by bago2k4** [comment]
@belucid right but the face pile was already working that way, i didn't touch at all that code, i think we can merge this and add another issue for the face pile to fix.
We have also to fix the uniqueness by avatar id for the repetition when commenting from Slack.
WYT?

**Comment by belucid** [comment]
OK @bago2k4 added both of these to https://trello.com/c/pR6wLnZJ

**Pull request merged**
