### PR TITLE
Section editing

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/957XqBVY

To test:
- run `lein test-all!`
- checkout tests for `test.open-company-web.finances.finances`, `test.open-company-web.growth.growth` and `test.open-company-web.simple-section`: they should cover a good part of the editing states
- check the code
- try to edit a simple section
- try to add a new section and save the edited data (this needs a fix on the API side: right now a PATCH with `:sections` and the new section doesn't return `:updated-at` and `:author`)
- try to edit a _finances_ section (it's guaranteed to update only title and notes for now)
- try to edit a _growth_ section (it updates only title and notes for now)
- merge if you like
- send a newsletter via torrent in clojurescript

### CODE REVIEW

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
Waiting on a new API PR.

**Comment by belucid** [comment]
+1 on all the namespace import cleanup

**Comment by belucid** [comment]
Looking good. Couple small improvements discussed in Slack.

**Comment by belucid** [comment]
If you remove a section then click to add (w/o a refresh in between) then the removed section is filtered out rather than in the list.

**Comment by belucid** [comment]
Leave placeholder text until user types and have focus on body field after an add.

**Comment by belucid** [comment]
Spacing is bad when a section title spans multiple lines:

http://take.ms/RiADg

**Comment by belucid** [comment]
Long title doesn't wrap in the ToC:

http://take.ms/Fsfff

**Comment by belucid** [comment]
Scroll to the section the user clicked in in the dialog. So for example, if I click the add in FINANCIAL or COMPANY it should be scrolled so those are what I see first in the list.

**Comment by belucid** [comment]
A test is failing.

Also see duplicate content after clicking previous on the uni.edn company (pull mainline):

http://take.ms/E6Wmc

**Comment by belucid** [comment]
Couple odd things I'm seeing on this branch:

 Section body font is 14px. That's new. Intentional?

The images (see Buffer) are no longer sized down and seem to be full size (this was an issue very early on that was addressed).

**Comment by bago2k4** [comment]
@belucid section title margin issue is fixed, i have also fixed some other small issues that came out with the new auto-growing textarea i'm using for the title

**Pull request merged**
