### PR TITLE
Medium punchlist 2

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/ls2TVAVJ

### CODE REVIEW

**Comment by belucid** [comment]
Reviewing.

**Comment by bago2k4** [comment]
@belucid finally tests are passing... this is ready i think if we agree on my comments here: https://docs.google.com/document/d/14t1lfelvVvlh68fv-iqKXvGT6B_08vbz5v3w9jZKyvo/edit?pli=1

**Comment by belucid** [comment]
@bago2k4 

- [ ] Can still nest bullets w/ pasting
- [ ] Fairly important new bug. If you are FoCE topic A, you can still click on topic B and go to its topic stream view (though everything is still disabled from the edit)

**Comment by belucid** [comment]
@bago2k4 

- [ ] this came in on GL https://sentry.io/opencompany/oc-staging-web/issues/206637255/

**Pull request merged**
