### PR TITLE
jwtoken expiration

### PR DESCRIPTION
**Pull request by martinklepsch**
based on #121 — [trello card](https://trello.com/c/BQw0hCd0/433-jwtoken-expiration-off-boarding-use-case)

This adds the capability to detect expired JWTokens and refresh them.

**To Test** (make sure you run auth: https://github.com/open-company/open-company-auth/pull/6)

- Sign out, sign in (so you have a token with an `:expire` field)
- Adjust the default value of 24 hours in the auth project to something small (30 seconds works well)
- Reload the app or trigger any other Xhr requests
- Look at the console and see a `"Refreshing JWToken"` message
- Look at the resources panel and check that the token is actually different

### CODE REVIEW

**Comment by belucid** [comment]
@martinklepsch please merge mainline

**Comment by belucid** [comment]
@martinklepsch bump

**Comment by martinklepsch** [comment]
@belucid updated

**Comment by belucid** [comment]
Reviewing.

**Pull request merged**
