### PR TITLE
444 feedbacks

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/kzyD2ctz

### CODE REVIEW

**Comment by belucid** [comment]
Reviewing

**Comment by belucid** [comment]
@bago2k4 

- [ ] I'm getting pencils on hover in the snapshot preview: http://take.ms/kTvlZ

**Comment by belucid** [comment]
@bago2k4 

- [ ] Cashflow doesn't have currency symbol http://take.ms/rC2yZ

**Comment by belucid** [comment]
@bago2k4 

- [ ] All images are being added at the bottom of the content. To test this, go to an existing topic, edit it, add a new paragraph between 2 existing ones. Add an image with the (+). Notice, the image is now at the bottom of the content.

**Comment by bago2k4** [comment]
@belucid now this is good

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@bago2k4 

- [ ] Can't edit with front of card pencil, it errors
- [ ] Improper warning sequence: 1) make an edit to a topic 2) click cancel, it warns you you have unsaved edits, it shouldn't when you manually hit cancel (as opposed to navigating away)
- [ ] Improper edits sequence: 1) make an edit to a topic 2) click cancel and OK 3) immediately click the pencil to edit the topic again. Notice your prior edits are still there, they shouldn't be.
- [ ] We should never show cents in Finance: http://take.ms/LPZXl

**Pull request merged**
