### PR TITLE
Topics layout

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/gWqTYiUQ

To test:
- [x] render 1 column
- [x] render 2 columns
- [x] render 3 columns
- [x] all working, no errors? good
- [x] when rendering 2 and 3 columns the component tries to reach a squared dashboard adding the next topic to the shortest column of the 2 or 3
- [x] check for externs errors on staging or beta

### CODE REVIEW

**Comment by belucid** [comment]
@bago2k4 please merge mainline

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@bago2k4 

- [ ] Snapshot renders as blank on this branch. Error is: ```:let [section-name (name (get (:3 best-layout) idx))]]``` doesn't support name in topics_columns.

**Comment by belucid** [comment]
@bago2k4 

- [ ] Also (and likely unrelated to this branch, probably happened w/ tooltip branch?) there's a problem now w/ showing the prior selected topics on the share snapshot screen. The prior ones (already in `:stakeholder-update`) don't show as selected, but then of course they are. Easiest way to see this is to go to Buffer, share a snapshot (notice, nothing is selected), pick just 1 topic, then preview, notice many are selected.

**Comment by bago2k4** [comment]
@belucid should be good now

**Comment by belucid** [comment]
@bago2k4 still force add topic to always be in the 3rd column

**Comment by belucid** [comment]
Reviewing.

**Pull request merged**
