### PR TITLE
Add sections

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/bfMlBt1p

to test:
- try to add a section with the link at the top of the ToC
- try to add a section btw other sections and check these facts:
  - the section is added in the right place if the categories match :heavy_check_mark:
  - the section is added at the top if the categories don't match :heavy_check_mark:
  - the category is added if it was empty :heavy_check_mark:
- check CI or run `lein test-all!`
- check the code
- merge

_NB_: saving a new added section is not part of this branch. Also when you select a new section and it gets added to the current list a js error is fired, i was unable to avoid this but the component that errors is unmounted right after so it should not be a problem. ping me for more info if you need

### CODE REVIEW

**Comment by belucid** [comment]
@bago2k4 please merge mainline in.

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
I don't see the no "Previous" gap fixed on this branch.

**Comment by belucid** [comment]
Section add is being attempted with a PUT, should be PATCH (using the partial-update rel).

**Comment by bago2k4** [comment]
@belucid sorry i merged again the style-fixes branch. But it shouldn't be a problem. About the PUT i didn't do any work on that, all the request you see are old, i was planning on working on the request while working on the section editing branch.

**Pull request merged**
