### PR TITLE
Carrot electron desktop application

### PR DESCRIPTION
**Pull request by cjsauer**
Trello: https://trello.com/c/V32yZS83/1955-desktop-electron-app

To test:
- Read through the [desktop documentation](https://github.com/open-company/open-company-web/tree/electron2#desktop-application)
- [x] Does it make sense?
- [x] Does it work?
- With your local carrot services running (including web), launch the development desktop build
- [x] Are you presented with the `Welcome to Carrot` screen? (you might need to clear your app storage if you've been testing desktop prior to this PR)
- [x] Slack login works?
- [x] Google login works?
- [x] Email login works?
- [x] Is logging in a smooth process? (no redirect loops, screen flickering, etc)
- In a web browser, log in with a different user of the same org
- Mention the desktop user in a comment
- [x] Does the Mac dock icon show a badge notification? (In development, the dock icon will not be the Carrot, but the Electron logo)
- [x] Can you clear the badge notification by viewing the comment?
- Create a post that contains a link external to Carrot
- [x] Does opening this link within the desktop client take you to your default web browser?
- Sign out of the desktop application
- [x] Are you redirected back to the `Welcome to Carrot` screen?
- Close the application window
- [x] Is the application still running?
- [x] Can you open the window again by clicking the dock icon?
- [x] Does CMD+Q fully quit the application?

### CODE REVIEW

**Comment by bago2k4** [comment]
@cjsauer so following the local developement steps i get this:

Screenshot 2019-07-03 at 1 02 13 PM

Output from command line says:
```
$ yarn start
yarn run v1.15.2
warning package.json: No license field
$ electron .
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by cjsauer** [comment]
@bago2k4 fixed. I'll have to find a different strategy for Windows support. I think I'll create a boot task specifically for production windows builds. It's likely the only task we'll need on Windows. I'll make a new branch/PR for that soon.

**Comment by bago2k4** [comment]
@cjsauer when you fix an issue in the PR please move it back in ready for review (add the label) so the assignee knows it's ready again.. this one i knew since you told me in Slack though

**Comment by bago2k4** [comment]
@cjsauer we are missing a link to go to the signup page in the login-wall component.

**Comment by bago2k4** [comment]
this is almost ready, i would like to give it another quick look monday morning since it's not needed over the weekend

**Pull request merged**
