### PR TITLE
Image uploads, highlighting, list formatting icons

### PR DESCRIPTION
**Pull request by martinklepsch**
[trello card](https://trello.com/c/RDvaxcSa/373-topic-editing-image-handling-highlights-edit-bar-icons)

- [x] Edit an existing topic, check that a plus appears left to the line you're on if the cursor is on an empty line
- [x] click on the plus and upload an image. Save the topic. Verify that the image is still there after a reload.
- [x] check that you can highlight (yellow background) chunks of text using the paint-brush button
- [x] check that the symbols for adding ordered/unordered lists are clear

I'm couldn't find anything better than the paint brush icon but maybe you see something that seems fitting here: https://fortawesome.github.io/Font-Awesome/

### CODE REVIEW

**Comment by belucid** [comment]
@martinklepsch I think the highlight icon you selected is the best of what's there from what I can tell. It works for now.

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@martinklepsch once you press (+) then move away from it the link hides (which is good) but it's still there and an active link http://take.ms/ozPJO

Would be better if it was truly gone.

**Comment by belucid** [comment]
Everything else looks good @martinklepsch 👍

**Comment by martinklepsch** [comment]
@belucid updated

**Pull request merged**
