### PR TITLE
Board creation

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/08kqHWiJ

To test:
- cleanup auth and storage DBs
- signup with email
- create an org
- visit a default board page and click the board settings icon
- do you see the slack mirror setup? you shouldn't
- signup with slack but do not connect the bot (deny second auth step on slack)
- create an org
- visit a default board page and click the board settings icon
- go to team settings (old UI) and add the bot to the slack org
- go back to the board page and open the board settings
- do you see the slack mirror setup now? you should!
- click create new board
- enter a name
- do you see the slack mirror setup? you shouldn't
- save the board
- open board settings modal
- do you see the slack mirror setup now? you should!
- try adding/removing the slack mirror and saving
- test comments mirroring for a random entry

### CODE REVIEW

**Comment by belucid** [comment]
- Sentry that came in during the call
- Remove newlines for truncation
- Use the stylekit white on grey tooltip everywhere

**Comment by belucid** [comment]
@bago2k4 tests are failing

**Comment by belucid** [comment]
@bago2k4 

- [ ] include private / public icon on board in left nav

**Comment by bago2k4** [comment]
@belucid yeah, cljsjs has a PR open, once that's merged tests will pass. Do you want me to downgrade raven here and wait for their PR before upgrading again?

**Comment by belucid** [comment]
@bago2k4 no, it's OK, they are usually pretty quick to merge.

**Comment by bago2k4** [comment]
@belucid revan upgrade was merged and tests are passing now.

**Comment by belucid** [comment]
Reviewing

**Comment by belucid** [comment]
@bago2k4 

- [ ] If you edit a shorter update to have more content (so to be longer) then click save, when the non-editable modal comes back the comment sidebar is too short: http://take.ms/ZSqoN

- [ ] When you delete a board, it works, but you are left in the (now deleted) board settings. Should nav. away to All Activity.

**Pull request merged**
