### PR TITLE
improve redirect logic on signup

### PR DESCRIPTION
**Pull request by martinklepsch**
[trello card](https://trello.com/c/5h8tjfIT/450-create-company-flow-for-newly-seen-org-id)

- improves the redirect logic when users sign up
   1. /create-company if they don't have a company yet
   2. redirect via cookie if present
   3. redirect to their company if they have exactly one
   4. redirect to /companies if they have multiple
- adds a few button helper classes that replace the custom styling for save/remove buttons
- improves design on /create-company page to be more in line with Mark's work

**To test**

- [x] log out
- [x] sign in with account that has no company
  - [x] do you get to to `/create-company`?
  - [x] is the name field prepopulated?
  - [x] when creating the company, are you redirected to the new dashboard?
- [x] sign out
- [x] sign in with account that has one or more companies
  - [x] do you get back to the page you were on before? great!

You can check this for the case that the redirect cookie doesn't exist as well but this is unlikely at best so maybe fine to not test explicitly (code is straightforward).

<span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_64.png);background-position:72.5% 27.5%;background-size:4100%" title="rocket"></span></span>

### CODE REVIEW

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@martinklepsch 

- [ ] name field doesn't pre-populate.

**Comment by martinklepsch** [comment]
@belucid Are you running the latest `mainline` of `auth`? Make sure you generate a new token as well. Previously tokens were missing the team name because of a typo in the auth service.

**Comment by belucid** [comment]
I'm def. on mainline of auth @martinklepsch 

I'll clear my token just to be sure, but I'm logging out, which should be enough to get a new token.

**Comment by belucid** [comment]
@martinklepsch 

Doesn't seem to default name, no.

- [ ] If they click "Back to OpenCompany" button, log them out

**Comment by martinklepsch** [comment]
@belucid ready again — I also modified the behavior of the sidebar logout button to bring users to `/`, let me know if you want that reverted.

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@bago2k4 Please finish this review.

**Comment by bago2k4** [comment]
@martinklepsch i think there one thing left:
- [ ] I shouldn't be able visit /create-company while i'm logged out (ie: no jwt cookie)

**Comment by bago2k4** [comment]
@martinklepsch please merge mainline

**Comment by martinklepsch** [comment]
@bago2k4 merged mainline, also tested again locally and not seeing any 500 errors

**Comment by bago2k4** [comment]
good what about my last comment? @martinklepsch

**Comment by martinklepsch** [comment]
@bago2k4 I agree that `/create-company` shouldn't be shown when logged out but haven't had time to do it yet

**Comment by belucid** [comment]
@bago2k4 maybe you can handle not showing on logout. @martinklepsch is out today.

**Comment by bago2k4** [comment]
moved the item about the /create-company when logged out to PR #152 . merging this

**Pull request merged**
