### PR TITLE
Email onboarding

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/1j8YU9cd

URLs:
- improved `/create-company`
- added `/:slug/settings/logo` (logo setup after company name setup to be wired yet)
- added `/email-confirmation` (email confirmation page)

For the rest of the screens follow the card and the screen in Zeplin (design _Onboarding with Email v3 2016 09 15_)

### CODE REVIEW

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@bago2k4 

- [ ] Footer isn't fixed to bottom of home page on long screens
- [ ] Footer isn't fixed to bottom of pricing page on long screens
- [ ] Get Started button should be OpenSans
- [ ] "OR SIGN IN VIA EMAIL" link should be in OpenSans and underlined (see our link style in Share URL dialog)
- [ ] Close button in sign-in dialog doesn't need circle and is too small and light, match what you just did for lightbox
- [ ] "DON'T HAVE AN ACCOUNT..." is too light in color and weight. "SIGN UP NOW" portion should be underlined (see our link style in Share URL dialog)
- [ ] FORGOT PASSWORD? should be underlined (see our link style in Share URL dialog)
- [ ] Match these dialog's styling to current share dialogs more, EMAIL and PASSWORD field labels should match style of "SHARE THIS PRIVATE LINK", "Sign In" header should have capitol "In" and match style of "Share a Link".
- [ ] Email field should have focus when Sign In (with email) dialog opens
- [ ] Sign up with email should take you to email signup dialog, now it takes you to email sign in

**Comment by belucid** [comment]
@bago2k4 

- [ ] New dialogs aren't totally consistent w/ the old when it comes to font, spacing, divider, X: http://take.ms/x6rRR
- [ ] Typo, Sign Up with email title says "Sign Un"
- [ ] footer is pushed down too low on a long screen on the pricing page http://take.ms/3Ccu5
- [ ] clicking SIGN IN / SIGN UP in header always shows you the home page even if you were on pricing or about... that could be OK, but the URL is left as what it was, which creates oddness. Should either leave you on the page you were on and show the dialog, or if showing the home page, update the URL too.

**Comment by bago2k4** [comment]
@belucid should be good now

**Comment by belucid** [comment]
@bago2k4 

- [ ] when we 401 on a company dashboard, we show the home page instead (good) but the URL stays as the company dashboard URL, e.g. `https://staging.opencompany.com/buff` (not good)

**Comment by bago2k4** [comment]
@belucid that's intended because, if the user can login, he gets redirected to the company page after logging in instead of the home (where there is a redirect too for logged in users: to /create-company if he has no companies, to their company page if they have only one or to /companies if he has more than one)

**Comment by belucid** [comment]
@bago2k4 

- [ ] when we 401 on a company dashboard, we show the home page, but instead we should show the prior full page login lander since the URL is still the company URL.

**Comment by belucid** [comment]
@bago2k4 

- [ ] Break the name field in the sign up by email into 2 parts (both on the same "row"), First Name and Last Name.

**Comment by bago2k4** [comment]
@belucid about this:
> when we 401 on a company dashboard, we show the home page, but instead we should show the prior full page login lander since the URL is still the company URL.

This was partially done, meaning that i show the old login wall on company dashboard but it has only the slack button (not the new login overlay). in #193 i did the rest of the work since there the login overlays are more accurate and they have also error handling moved from this login screen to the login overlay

**Comment by bago2k4** [comment]
@belucid ready again

**Comment by bago2k4** [comment]
[Email on boarding UI work](https://trello.com/c/1j8YU9cd/627-email-on-boarding-ui-work)

**Comment by belucid** [comment]
@bago2k4 please resolve mainline conflict.

**Comment by belucid** [comment]
@bago2k4 please resolve mainline conflict.

**Comment by bago2k4** [comment]
@belucid done

**Pull request closed without merging**
