### PR TITLE
Remove unused email waitlist stuff

### PR DESCRIPTION
**Pull request by belucid**
Review with https://github.com/belucid/open-company-infrastructure/pull/112

[Trello](https://trello.com/c/LYYr7EgP)

Code cleanup.

To test... 

- Deploy to staging using the infra branch linked above
- Load the homepage
- scroll down to the slack/email switch
- [x] does the switch work when you click the green arrow? Good
- [x] does the switch work when you click the Slack/Email buttons on the right? Good
- [x] does the video lightbox work? Good
- [x] same on mobile?
- now load the pricing page
- [x] does the pricing switch works (monthly/annual switch)? Good
- [x] same on mobile?
- now load /login
- dismiss the login overlay
- scroll to the email/slack switch
- [ ] does it work? Good
- [x] does the video lightbox work? Good
- [x] click pricing in the top navbar (use it to make sure you are using internal nav)
- [x] monthly/annual switch works? Good
- [x] Start the NUX'ing of a new company from the home page. Enter the flow OK?

### CODE REVIEW

**Comment by belucid** [comment]
[Code cleanup: email waitlist](https://trello.com/c/LYYr7EgP/2112-code-cleanup-email-waitlist)

**Comment by belucid** [comment]
@bago2k4 I'll review it again.

**Comment by belucid** [comment]
@bago2k4 Just one issue found here:

- Try the green arrow slack switcher on big web, works?
- Open the login overlay
- Close the login overlay
- Try the green arrow slack switcher on big web. It no longer works.

**Comment by bago2k4** [comment]
@belucid good catch, the click handlers were set 2 times so the first was switching to Slack but the second was switching back to Email. Nothing was happening visually

**Pull request merged**
