### PR TITLE
One column snapshot

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/dJOZKqMS

This is missing the connection with martin's work about email share. We think it's better to merge both our work in and resolve the conflicts then link the 2 things together.
So here the email link does nothing other then PATCHing the new SU sections.

### CODE REVIEW

**Comment by bago2k4** [comment]
@belucid ready

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
- [ ] Snapshot itself (viewing on web) needs to be 1 column too
- [ ] image needs to go to the edge of the card http://take.ms/Gm0M3
- [ ] on a wide screen, why are the cards so narrow? http://take.ms/HUGdr
- [ ] 3 share to buttons/links/items/thingamabobs should disable if user removes all topics

**Comment by belucid** [comment]
@bago2k4 

- [ ] Snapshot itself (viewing on web) needs to be 1 column too
- [ ] image needs to go to the edge of the card http://take.ms/Gm0M3
- [ ] on a wide screen, why are the cards so narrow? http://take.ms/HUGdr
- [ ] 3 share to buttons/links/items/thingamabobs should disable if user removes all topics

**Comment by bago2k4** [comment]
@belucid ready again

**Comment by belucid** [comment]
@bago2k4 

- [ ] on 1 column snapshots I’m still not seeing anything wider than a 400px card. The topic row goes to 500px, but the topic-internal is only 400px
- [ ] could be related to item above, but the drag shadow thingy should match the width of the card
- [ ] Need a bottom gap below drag shadow thingy http://take.ms/xuQRg

**Comment by belucid** [comment]
@bago2k4 please merge mainline

**Comment by belucid** [comment]
@bago2k4 sorry... please merge again.

**Comment by belucid** [comment]
@bago2k4 you can wire up the email dialog now, it's in mainline

**Comment by bago2k4** [comment]
@belucid all issues solved, mainline merged, email button connected to martin's UI

**Comment by belucid** [comment]
👍

**Pull request merged**
