### PR TITLE
People profiles

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/l475dqLY

Related PRs:
- ~[Storage](https://github.com/open-company/open-company-storage/pull/246)~
- ~[Auth](https://github.com/open-company/open-company-auth/pull/106)~
- ~[Lib](https://github.com/open-company/open-company-lib/pull/84)~

NB: this also contains a fix to make sure we always get the larger avatar possible from Slack

### CODE REVIEW

**Comment by bago2k4** [comment]
[People / profiles](https://trello.com/c/l475dqLY/2072-people-profiles)

**Comment by belucid** [comment]
@bago2k4 let's use the normal bottom left confirmation to confirm a profile save was successful

**Comment by belucid** [comment]
@bago2k4 need hover states for the profile pop-up buttons

**Comment by bago2k4** [comment]
@belucid conflict is fixed

**Pull request merged**
