### PR TITLE
Share modal

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/5Ih7K2Yd

To test:
- share link
- share email
- share slack:
   * with a slack user w/o bot added
   * with a slack user w/ the bot added
   * with an email user

NB: if you merge this after #282 you need to change the line 11 of src/oc/web/components/ui/activity_share.cljs from:
`[oc.web.components.ui.mixins :as mixins]`
to
`[oc.web.mixins.ui :as mixins]`

### CODE REVIEW

**Comment by bago2k4** [comment]
[Share from FoC](https://trello.com/c/5Ih7K2Yd/1092-share-from-foc)

**Comment by thepug** [comment]
When testing the slack share where slack is disabled and I'm only using an email user I get the following:

carrot_-_grow_together

I'm still able to see the slack button and I get strange warning icon but no tooltip.

**Comment by bago2k4** [comment]
@thepug i had still the testing check, i inverted the slack disable check.
Now it should be right, other improvements and fixes have been added from the feedback doc
https://docs.google.com/document/d/1X3j869Y8n94zfqaGVhrWf8VOlr3qEa_4a1fxtIjH6fs/edit

**Comment by thepug** [comment]
https://opencompanyhq.slack.com/archives/C0FGNSA2V/p1510762749000776

- [ ] Clear the fields once you have shared in an email

**Pull request merged**
