### PR TITLE
Topic list edit

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/cqXKTI8w

NB: this branch also make an effort in the direction of losing jQuery for good. It is still loaded from index.html for now since some old components are still using it but all the new components used in the dashboard doesn't use it anymore.

To test:
- navigate to the dashboard
- tap the bottom button "Manage topics"
- try to reorder the topics
- active/deactivate some topics
- test both button in the navbar: Cancel and Save

### CODE REVIEW

**Comment by bago2k4** [comment]
@belucid hold on, making some cleaning and adding tests for the sortable list component

**Comment by belucid** [comment]
@bago2k4 is this ready to look at?

**Comment by bago2k4** [comment]
@belucid it is, sorry i forgot to update it here

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@bago2k4 manage topics is shown while the company data is loading, shouldn't be.

**Comment by belucid** [comment]
@bago2k4 style manage path like a plain card (see `/OpenCompany Design/Mocks by Date/2016 - February/version 2/Scrolled.png`) but with the text still "Manage Topics".

**Comment by belucid** [comment]
@bago2k4 clicking on Manage Topics, I get an error:

http://take.ms/mN9mm

**Comment by bago2k4** [comment]
@belucid should be good now

**Comment by belucid** [comment]
@bago2k4 please merge in mainline

**Comment by bago2k4** [comment]
@belucid merged

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@bago2k4 the D'n'D' to reorder seems to be working well.

**Comment by belucid** [comment]
@bago2k4 I can't click the checkboxes to add or remove sections, when I do nothing happens.

**Comment by belucid** [comment]
@bago2k4 on this branch, there's no content shown in the dashboard for the topics (before you click "Manage Topic") except for "just now" (at least for Buffer on staging).

**Comment by belucid** [comment]
@bago2k4 should be seeing title and descriptions on the section selectors once "Manage Topics" has been clicked. I only see titles.

**Comment by bago2k4** [comment]
@belucid addressed all the issues. also i had the same problem you described on the topic list (before clicking "Manage Topic") and i fixed it, i'm not sure why on staging it worked.

**Comment by belucid** [comment]
@bago2k4 D'n'D seems good on big web (Chrome) but doesn't work at all on iOS Safari.

**Comment by belucid** [comment]
@bago2k4 "Progress" category seems good w/ the topics available for selection, but "Financial" and "Company" categories are borked. (See Pied Piper and Buffer for example).

**Comment by belucid** [comment]
@bago2k4 Don't show company name or description when they are editing topics. Just the "Cancel" / "Save" and the category nav.

**Comment by belucid** [comment]
@bago2k4 Don't show "Save" until they make a change that needs saved.

**Comment by belucid** [comment]
@bago2k4 Don't show the D'n'D' bars on topics that aren't selected (and don't let them be D'n'D'd). Display all unselected topics below the selected topics.

**Comment by belucid** [comment]
@bago2k4 Can no longer add a topic from the old UI. There's an error. It's not directly related to the card/PR, but it's about topic list editing, so let's fix it here.

http://take.ms/oxI1q

Also the old UI shows every topic in the add topic dialog now, not just the missing ones... could be related to the above?

**Comment by bago2k4** [comment]
@belucid can't see what you mean here:
_"Financial" and "Company" categories are borked. (See Pied Piper and Buffer for example)._

**Comment by belucid** [comment]
@bago2k4 it looks like the "borked" problem is when you try to switch categories while manage topics is active.

**Comment by belucid** [comment]
@bago2k4 the category nav. ought to “stick” to the top when you’re managing topics like it does when you aren’t. Right now it scrolls away too.

**Comment by belucid** [comment]
@bago2k4 the "Save" button enables in "Manage Topics" if you select a new topic, but not if you just unselect an existing topic. It should enable for that case too.

**Comment by belucid** [comment]
@bago2k4 if a category has no top topics already you don't get the manage topics button. Need to.

**Comment by belucid** [comment]
@bago2k4 tests aren't passing on this one.

**Pull request merged**
