### PR TITLE
User management

### PR DESCRIPTION
**Pull request by bago2k4**
Placeholder for feedback

### CODE REVIEW

**Comment by bago2k4** [comment]
[User Management](https://trello.com/c/KxL4Pk3h/655-user-management)

**Comment by belucid** [comment]
@bago2k4 

- [ ] No request to enumerate users in settings?

- [ ] Logged into normal OC Slack org. No Slack Org showing in user settings: http://take.ms/A7fCY

Styling on User Profile page is correct ( http://take.ms/rKziQ ) styling on company settings page is off:

- [ ] Label fonts should match "NAME", "SLACK ORG..", "EMAIL" from profile page: http://take.ms/S5xd8
- [ ] Put logo in a box (exactly match how we display it on header), put more space between logo and 2 image manipulation icons.
- [ ] Have the image manipulation icons' tooltips open to the bottom of the icon.
- [ ] Use the same component/behavior for handling email addresses input as we have in email share
- [ ] Change button copy to just "SEND INVITES". Button should be disabled until there is a valid email address.
- [ ] Match white space between label and field of invite users to the fields above: http://take.ms/WqFLj
- [ ] Styling of user management explanation copy should match "User information is from your Slack account." from user profile: http://take.ms/oy0WO

Copy needs updated:

- [ ] Update user management copy for `auth-source` `slack` user (see below)
- [ ] Update user management copy for `auth-source` `email` user (see below)

Slack copy:

Users can add and edit topics, and they can share updates with others.

All members of your Slack organization (not guests) can authenticate as users. You can also invite users to join by email.

Email copy:

Users can add and edit topics, and they can share updates with others.

**Comment by belucid** [comment]
@bago2k4 

- [ ] User option on a dashboard load that API `401`s is to logout (keep URL in redirect)

**Comment by bago2k4** [comment]
[New User Invite](https://trello.com/c/rWmzHAzC/673-new-user-invite)

**Comment by belucid** [comment]
@bago2k4 

- [ ] SIGN UP / SIGN IN in header is Domine, should be Open Sans and match styling of PRICING, ABOUT etc.
- [ ] At `/` there is a HOME link in the header, that should only be there on other pages such as pricing and about.

**Comment by bago2k4** [comment]
[New User Signup via Invite](https://trello.com/c/9QUsPPlw/657-new-user-signup-via-invite)

**Comment by belucid** [comment]
@bago2k4 same conflict.

**Comment by bago2k4** [comment]
@belucid done

**Pull request closed without merging**
