### PR TITLE
Finances editing

### PR DESCRIPTION
**Pull request by bago2k4**
cards:
- https://trello.com/c/L6LB7xO3
- https://trello.com/c/SEaCUpna

To test:
- import bago company from api
- open /companies/bago
- do you see the charts for finances and growth?
- can you navigate back in the chart on each metric/link?
- does all the values seem fine?
- try to edit the finances data
- open buffer and try to edit the finances data: here you should see the last 12 month editable even if there are less than 12 values initially
- change some values and some other using the more button at the bottom of the table
- save
- is everything ok?
- run the tests or check the CI
- merge

### CODE REVIEW

**Comment by belucid** [comment]
@bago2k4 here are some comments on editing: http://cl.ly/image/193c180D3Q0M/finances.png

**Comment by belucid** [comment]
@bago2k4 pull before revising, I made a few minor tweaks.

**Comment by belucid** [comment]
@bago2k4 here are some comments on runway display: http://cl.ly/image/2g2R3r1O2a37/finance%20display.png

**Comment by bago2k4** [comment]
@belucid this is ready to be reviewed again, there is only one issue that i didn't fix: the separated finances editing (title/notes vs. data). I'll fix it in PR #54

**Pull request merged**
