### PR TITLE
Follow-ups

### PR DESCRIPTION
**Pull request by bago2k4**
Related PRs:
- [Storage](https://github.com/open-company/open-company-storage/pull/211)
- [Digest](https://github.com/open-company/open-company-digest/pull/25)
- [Email](https://github.com/open-company/open-company-email/pull/54)
- [Bot](https://github.com/open-company/open-company-bot/pull/87)
- [Lib](https://github.com/open-company/open-company-lib/pull/68)
- [Notify](https://github.com/open-company/open-company-notify/pull/12)

To test:
- add a post with follow-ups in a team section
- [x] default follow-up are all users but you
- [x] make sure all other users get an in app notification
- [x] make sure all other users get an email or a Slack notification
- add a post with follow-ups in a private section
- [x] default follow-up are all section users but you
- [x] make sure all other users get an in app notification
- [x] make sure all other users get an email or a Slack notification
- publish a post with only some follow-ups (not all possible users)
- edit the post and include the remaining follow-ups
- [x] make sure the added users get the notification
- complete some follow-ups of a post
- edit the post
- [x] make sure you can't remove the follow-ups for the user that have completed them
- [x] make sure you can't remove follow-ups for users that have added it for themself

### CODE REVIEW

**Comment by belucid** [comment]
@bago2k4 merge conflicts here

**Comment by bago2k4** [comment]
[Follow-ups, cont...](https://trello.com/c/jJdzV8pj/2108-follow-ups-cont)

**Comment by belucid** [comment]
@bago2k4 Save in the follow-ups dialog on a new post breaks auto-save.

Sequence:

- In a section
- Use QP to create a new post
- Add a title and body
- Add followups
- Exit the followups dialog with save
- Notice "Saving..." is stuck
- Notice new edits don't auto-save any more

**Comment by belucid** [comment]
@bago2k4 Funny edge case:

- Create follow-ups with a post
- But add yourself, and remove 1 other
- You get the "for everyone" message, but it wasn't for everyone, you left 1 out

**Comment by belucid** [comment]
@bago2k4 also need a merge conflict thrashing

**Comment by belucid** [comment]
@bago2k4 

This test step @iacopo: "make sure you can't remove follow-ups for users that have added it for themself"

Silently fails. UI looks like it'll work, it let's you remove them and save, but then if you go back and check, they still have it. Should be disabled like a completed one.

**Comment by belucid** [comment]
@bago2k4 this is looking good except for:

Editing a post with a follow-up created by another user for themselves.
With yesterday's change, the checklist toggle is disabled in that case. That's good.
But the checkbox isn't checked, which seems odd, even though the toolip on hover is "Follow-up created". Should be checked.

**Comment by belucid** [comment]
@bago2k4 we shouldn't show the blue bar on post edit if the only follow-up is by user(s) for themselves.

**Pull request merged**
