### PR TITLE
Api integration

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/WLDgwPjX

use the api to load data to show.

- load [localhost:3449](http://localhost:3449), the list of companies should be empty
- add a couple of companies
- reload [localhost:3449](http://localhost:3449), now you should see 2 companies
- click on one, you should only the name of the company
- add a couple of reports for the company
- reload the page, now you should see 2 reports in the list
- click on one, the report should load
- go back and click on the other
- all good? no errors in the console?
- load a company that does not exist: [localhost:3449/companies/BAGO](http://localhost:3449/companies/BAGO)
- load a report that does not exist: [localhost:3449/companies/OPEN/2014/Q8](http://localhost:3449/companies/OPEN/2014/Q8)
- all well? merge

### CODE REVIEW

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
We don't have to use (get ...), when the key is a string can just reverse the order. (:key hash) works and of course ("key" hash) doesn't, but (hash "key") does:

```clojure
({"compensation" 100} "compensation")
100
```

Not a big deal... just keeps the code a little tidier without all the (gets ...)

The other option is when the data comes in from the API you can keywordize it:

```clojure
(clojure.walk/keywordize-keys {"foo" "bar"})
{:foo "bar"}
```

**Comment by belucid** [comment]
Merging this, but let's go back to the keyword data lookup rather than `(get ...)`. Use the keywordize-keys approach on the parsed JSON.

**Comment by belucid** [comment]
@bago2k4 you going to make the updates write back next?

**Comment by bago2k4** [comment]
@belucid yeah i'll change it to use the keywordize-keys tomorrow. i was using `get` because it looked like `(coll "string-key")` was failing if the key was not present but the keywordize approach is better..

**Pull request merged**
