### PR TITLE
UX desktop: drafts click

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/OoJc5Qtd

To test:
- [x] expand a post, did it work? Good
- click on New
- add a long body
- do NOT publish it, close Cmail
- click New again
- add a short body (1 line)
- do NOT publish it, close Cmail
- go to drafts
- click on the first draft
- [x] did it open in edit mode? Good
- click on the second
- [x] did it open in edit mode? Good
- now publish both
- go to AP
- click on both bodies
- [x] does the long one expanded? Good
- [x] do you see your view in WST? Good

### CODE REVIEW

**Comment by bago2k4** [comment]
[UX desktop: draft click](https://trello.com/c/OoJc5Qtd/1874-ux-desktop-draft-click)

**Comment by belucid** [comment]
@bago2k4 Problem sequence:

- have a draft post in drafts
- click anywhere in the FoC (not on the Continue editing link)
- [ ] post opens? Good!
- close the CMail for the post
- [ ] post opens? Good
- click anywhere in the FoC (not on the Continue editing link)

Post no longer opens, you have to use the Continue editing link.

**Comment by belucid** [comment]
@bago2k4 hold up on this one, I think I did the sequence on the wrong branch

**Comment by belucid** [comment]
Actually @bago2k4 turns out the issue has to do with where I'm clicking on the card. I can click on the title, body or continue editing to edit the draft, clicking elsewhere on the card doesn't do it.

Should be able to click anywhere on the card, as long as it's not "Delete draft" it should edit it.

**Comment by bago2k4** [comment]
@belucid if you are ok with not doing the same change on mobile (ie: on mobile edit draft is opened only when user clicks on Continue editing) then this is ready

**Pull request merged**
