### PR TITLE
Email auth

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/eGUuJSaP

This branch add UI to let the user login with email and password. It also update some expect of JWToken retrieve when logging in with slack and where the refresh token url is coming from.

Corner case test (this should have been in email-onboarding but it was throwing a circular dependencies error):
- open buff.edn in API
- change the :public flag to true
- import buffer
- remove your JWToken (logout)
- go to /buff
- can you see a general login/signup button at top right instead of the slack button? good
- press it, can you login with slack and email? good

### NB: this branch starts from [email-onboarding](https://github.com/open-company/open-company-web/pull/188) branch so merge that first or review both PRs.

### CODE REVIEW

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@bago2k4 

- [ ] Fail to auth. Close the window. Come back into Sign in again. The error message is still showing.

Rest looks good.

**Comment by bago2k4** [comment]
@belucid fixed the above issue

**Comment by bago2k4** [comment]
[Brand New User Signup](https://trello.com/c/2zJG6EPK/654-brand-new-user-signup)

**Comment by bago2k4** [comment]
[Brand New User Signup](https://trello.com/c/2zJG6EPK/654-brand-new-user-signup)

**Comment by bago2k4** [comment]
[Update UI for email / password authentication](https://trello.com/c/eGUuJSaP/648-update-ui-for-email-password-authentication)

**Comment by belucid** [comment]
@bago2k4 

- [ ] merge conflicts
- [ ] set input field type to email for iOS keyboards, and no capitalizing
- [ ] Tab should go to password field

**Comment by bago2k4** [comment]
@belucid should be good again

**Comment by belucid** [comment]
@bago2k4 same mainline conflict as email-onboarding branch.

**Comment by bago2k4** [comment]
@belucid done

**Pull request closed without merging**
