### PR TITLE
Access control enhancements and Boards

### PR DESCRIPTION
**Pull request by bago2k4**
Trello cards:
https://trello.com/c/DgZPaV90
https://trello.com/c/DQDPbcNg
https://trello.com/c/ihjBQDRs
https://trello.com/c/htV1KDYO
https://trello.com/c/w6Pp1gnP
https://trello.com/c/3oSOhvfa

This PR is needed to support the access control changes made in Auth and Api services. It introduces the concept of team, organization and board.
Also this move all the old code from `open-company-web` to the new `oc.web` namespace for 2 main reasons:
- respect the namespace pattern we use in all the other services
- move all the needed code and leave out the old not anymore necessary code and components

Also this tries to make another step ahead in the move from Om to Rum since it migrates some components.

### CODE REVIEW

**Comment by bago2k4** [comment]
[OC Org Dropdown (replaces /orgs)](https://trello.com/c/ADd5CGHG/796-oc-org-dropdown-replaces-orgs)

**Comment by belucid** [comment]
@bago2k4 tests are broken on this one.

**Comment by bago2k4** [comment]
[Not 404’ing on bad slug (org, board, update)](https://trello.com/c/UANMoEVb/799-not-404-ing-on-bad-slug-org-board-update)

**Comment by bago2k4** [comment]
@belucid tests fixed 💣

**Comment by belucid** [comment]
@bago2k4 tests failing again.

**Comment by belucid** [comment]
@bago2k4 Reviewing.

**Comment by bago2k4** [comment]
Once this https://github.com/cljsjs/packages/pull/1069 is merged tests should be ok.. now they fail because it can't find the package on clojars.

**Comment by bago2k4** [comment]
[Remove separate emoji image loads](https://trello.com/c/6oWmPwmS/771-remove-separate-emoji-image-loads)

**Comment by bago2k4** [comment]
[Infinite loop in growth charting](https://trello.com/c/5sOxYqz7/801-infinite-loop-in-growth-charting)

**Pull request merged**
