### PR TITLE
Fix pluralization

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/kVljZV8s

try to insert 1 in the headcount fields, pluralisation should work here. it should not in finances and compensation.
Also try to insert a string that is not a number (eg: asd) in any field, it should count it as 0 and replace it with 0 with you press Enter.

### CODE REVIEW

**Comment by belucid** [comment]
Pluralization seems to be working on the report-editable-line now.

It's not quite right on the report-line (sums).

Headcount is a word that never pluralizes. So it should be:

0 total headcount
1 total headcount
10 total headcount

Full-time equivalents does pluralize, but it's not doing it properly. Should be:

0 full-time equivalents
1 full-time equivalent
2+ full-time equivalents

**Comment by belucid** [comment]
Compensation label ought to change to match the headcount label. For example, if I set it as 1 founder, it should say "founder compensation this month". If I set any category as 0, that line item should just go away in the compensation section. So if I set 0 executives, there should be no executives line in compensation.

**Comment by belucid** [comment]
The replacement of a string ("abc") with 0 works, but only on click back into the field, not on tab out.

**Comment by belucid** [comment]
Strap space after "headcount" before the ",".

**Comment by bago2k4** [comment]
remove "headcount" from total: 16 total, 12.5 full-time equivalents

**Comment by bago2k4** [comment]
@belucid should be good to go.
Tab is still not selecting the next field. it jumps directly to the comment box.
this is happening because the real input fields are hidden until the user click on the black underlined label.
If you want it please card it on trello and i'll work on it asap.

**Comment by belucid** [comment]
@bago2k4 please merge.

**Comment by bago2k4** [comment]
@belucid merged

**Comment by belucid** [comment]
@bago2k4 some remaining issues:

http://cl.ly/image/0Z2V0h361H25/localhost_3449_edit_open-company.png

**Comment by belucid** [comment]
@bago2k4 Remove lneed for legend pagination: http://cl.ly/image/173J1C3q0D1a/localhost_3449_edit_open-company-1.png

**Comment by belucid** [comment]
@bago2k4 When 0'ing out an employee type in the headcount section, also 0 out that category in compensation, otherwise there is "ghost" compensation that you can't edit.
http://cl.ly/image/2F1x1s1o030K/localhost_3449_edit_open-company-2.png

**Comment by belucid** [comment]
@bago2k4 merge in mainline.

**Comment by bago2k4** [comment]
@belucid try again :smile:

**Comment by belucid** [comment]
@bago2k4 Groovy!

**Pull request merged**
