### PR TITLE
Early code cleanup

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/ZyAv8cYx/187-ui-earlier-code-cleanup

Most of the changes where suggested by kibit that now run also in CI.
Test:
- compile and run the dev env
- check that the site works
- try to make some changes to different companies just to make sure it works
- check travis

### CODE REVIEW

**Comment by bago2k4** [comment]
@belucid this is ready. there are still 3 places where `loop` is used, today i don't have anymore time to look into them. Let me know if you want to merge it or wait for me to finish it.
Here are the loops:
https://github.com/open-company/open-company-web/blob/early-code-cleanup/src/open_company_web/lib/utils.cljs#L189
https://github.com/open-company/open-company-web/blob/early-code-cleanup/src/open_company_web/lib/utils.cljs#L189
https://github.com/open-company/open-company-web/blob/early-code-cleanup/src/open_company_web/lib/utils.cljs#L341

**Comment by belucid** [comment]
@bago2k4 please merge in mainline

**Comment by belucid** [comment]
@bago2k4 please look into the loops

**Comment by bago2k4** [comment]
@belucid the only loop i see now are for the async wait cycles.

**Comment by belucid** [comment]
@bago2k4 groovy

**Comment by belucid** [comment]
Reviewing.

**Pull request merged**
