### PR TITLE
Finances & growth tweaks

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/Q24IPZkw

Tooltips removed for all buttons when on mobile or tablet.

### CODE REVIEW

**Comment by belucid** [comment]
@bago2k4 haven't you done the opposite here? This removes the tooltips except when you are on mobile/tablet, rather than when you are.

**Comment by bago2k4** [comment]
@belucid yup sorry i didn't test it.. now should be good

**Comment by bago2k4** [comment]
PR reviews FTW

**Comment by bago2k4** [comment]
[Finance / Growth Tweaks](https://trello.com/c/Q24IPZkw/653-finance-growth-tweaks)

**Pull request merged**
