### PR TITLE
Design feedback part Deux

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/9uNFVm0S

NB: the Login Screen is used in 3 places:
- [home screen](http://take.ms/ZS8Hv) (for not logged in users, logged in users are redirected to their company/ies) 
- [not accessible dashboard](https://d1ro8r1rbfn3jf.cloudfront.net/ms_85656/PcEPd1NBW9W6ELU5ktjl1uwIVdfETq/OpenCompany%2B-%2BStartup%2BTransparency%2BMade%2BSimple%2B2016-07-04%2B08-47-59.png?Expires=1467722978&Signature=jbtsh4lt3m~lt~2186n2lY5TAiThgxyx2weWaC8UWpCDhTf3uwBKgOXEw3s3w5fxoxLUk-bc3XXZaGiE59jqBaefalWoVYPrTDW5SLeDRhaLfMy-XiGheeaSsl9s1TYQiGEWYx2ITL~iXJlL5llbqdu9mf1u2FDwjV81aYA-vsJ0qS8KNEa5qOgT83zGtrvOqDVSZ7Q8M0KxRs5gQuLAlOxKWY6bZmtpo6yDYvmaO4KQ~LqRGSElDCIuBSt4DR-zCR3kdyxrpxHf6FcX9xOO8kn-nNySryHuK6MBZqJRFUv68NkqvmrKmDgC2orlcgUnSqg7e9D8hSS64rw4ODaKGA__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA) when logged in (prompt to sign in with different slack account) 
- [not accessible dashboard when not logged in](https://d1ro8r1rbfn3jf.cloudfront.net/ms_85656/ZY6pi2f8Oj8FQVzNORdhHGtJbhpsjK/OpenCompany%2B-%2BStartup%2BTransparency%2BMade%2BSimple%2B2016-07-04%2B08-50-52.png?Expires=1467723062&Signature=fJoar5ZE7S47FymvSSSdZd2tSCdTMz5rtyC6VEtw1Kt9iFFYH8YkbqWSuxfNdCZdb1WwiIduB3Nn79x7Up3O5TFbj8zcV7aCzdVh3eZPFQEEETmafEFd9OvXqDCvGZ2KDE-MeBe7H-vPfLg-EzZ-eijgAa9TPG-NgP5OXpjKwNdCWyzE88CS2n2LshTLLpvXGJbzd5eYWPm7neULoICStWHb7ktXYHFcyqYFrQQItuCBvy-HXIohPo9Ae8ECjUosStnj7zr30egOjoLjEoy81bYzh~-mXhbk0Hz0g-FGjSWHarC8ba5fSKzSwCwKqxUQ9ckpDp9YlYRfylPdt7gQmQ__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)
I'm not sure this is what we want but the component was already used in these 3 cases. I changed the layout but the CTA in the first 2 cases are still the same.

To test follow the steps in the trello card.

### CODE REVIEW

**Comment by belucid** [comment]
@bago2k4 please merge mainline

**Comment by bago2k4** [comment]
@belucid ready

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@bago2k4 

- [ ] pull
- [ ] Share this Private URL dialog missing the closing X
- [ ] yellow bar issue on login page http://take.ms/EqOGR
- [ ] Font variables mis-leading. Make Domine default for body.
- [ ] Footer is too far down on long login screen page http://take.ms/OFkp9
- [ ] `/companies` should have footer

**Comment by bago2k4** [comment]
@belucid this is ready again. let me know if you notice any wrong font

**Comment by belucid** [comment]
@bago2k4 

Two problem sequence:

* Logout
* go to '/new'
* click the <- OpenCompany.com button once (notice, nothing happens)
* click the <- OpenCompany.com button again
* you get infinite spinner

**Comment by belucid** [comment]
@bago2k4 

- [ ] pull
- [ ] CONTACT link in footer is Domine, should be OpenSans
- [ ] 4th case `/login?access=denied` should get yellow bar and footer too (it doesn't)
- [ ] `/create-company` onboarding sequence should have top yellow bar
- [ ] Finances component: "$255,143" and "CASH - MAY 2015" should be OpenSans, it's Domine. Pillbox link text "CASH" should be all caps and OpenSans, it's mixed case and Domine.
- [ ] Growth component: "2,511,292" and "USERS - JUN 2015" should be all caps and OpenSans, it's mixed case and Domine. Pillbox link text "USERS" should be all caps and OpenSans, it's mixed case and Domine.
- [ ] Section history navigation links should be OpenSans, they are Domine
- [ ] "SAVE" "CANCEL" and "ARCHIVE THIS TOPIC" buttons in edit should be OpenSans, they are Domine
- [ ] Column and Row headers and cell data and More... in Finance and Growth edit tables should be OpenSans, they are Domine

**Comment by belucid** [comment]
@bago2k4 

- [ ] Yellow header buttons (PREVIEW AND SHARE, SHARE ON SLACK) are Domine, should be OpenSans

**Comment by belucid** [comment]
@bago2k4 

- [ ] Yellow dialog buttons (SEND, CANCEL, etc.) are Domine, should be OpenSans

**Comment by bago2k4** [comment]
@belucid now font should be fine everywhere.. not only where you mentioned. i changed the font back to the default Domino everywhere then where there was bold i changed the font to OpenSans. This should cover all the places (or the 99% of them)

**Comment by belucid** [comment]
@bago2k4 the 2 problem sequence describe above still exists

**Comment by belucid** [comment]
@bago2k4 

- [ ] the 2 problem sequence describe above still exists
- [ ] Drawer menu items are Domine, should be OpenSans
- [ ] Let's use the "standard" slack button we use on the login page here http://take.ms/EUIJi
- [ ] footer not at bottom on long access denied login page http://take.ms/mXZ0v
- [ ] finance/growth data in table cells should be OpenSans http://take.ms/banfM
- [ ] keep long x00,000+ negative values from having a line break http://take.ms/banfM

**Comment by belucid** [comment]
@bago2k4 

- [ ] Company name in header should be Domine

**Comment by bago2k4** [comment]
@belucid done

**Pull request merged**
