### PR TITLE
Stream view fixes

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/nxgQU1ki

Fix some spacing issues, make sure the attachments are always at the bottom of the stream view item, don't scroll comments to the bottom in the stream view.

Abstract: https://share.goabstract.com/dd1dcfe9-0abc-4c28-bdf0-94c1a6cbcd29

### CODE REVIEW

**Comment by bago2k4** [comment]
[Jelly UX: Stream view refinements and fixes](https://trello.com/c/nxgQU1ki/1183-jelly-ux-stream-view-refinements-and-fixes)

**Comment by belucid** [comment]
Starting review, another fix coming in around comment spinner.

**Comment by bago2k4** [comment]
@belucid fix is in

**Comment by belucid** [comment]
@bago2k4 I'll leave this open for now since presumably you want to put some of the stuff from the call in here (such as placement of the comment box), but whenever you want me to finish the review, just let me know here.

**Comment by bago2k4** [comment]
@belucid i think this is good to review again, check the trello card to see what i added (the last 3 checklist items).
I decided to work the add comment placement in another branch since i need a couple more sketches from Ryan for it and also it won't be a very small change, it's worth a PR

**Pull request merged**
