### PR TITLE
Update style

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/HRG7JfPO

### NB: merge after #212.

### CODE REVIEW

**Comment by bago2k4** [comment]
[Update “style"](https://trello.com/c/HRG7JfPO/735-update-style)

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@bago2k4 

- [ ] white box that shouldn't be there when there are no updates http://take.ms/Hp6IT
- [ ] white box appears while update isn't rendered (different than the yellow spinner that appears while update is being loaded from network

**Comment by belucid** [comment]
@bago2k4 

- [ ] Align topic selection w/ top of white box http://take.ms/HF7pk
- [ ] Align prior updates list w/ top of white box http://take.ms/TiXUv

**Pull request merged**
