### PR TITLE
Topic edit

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/FiGpHNm4

This use tinyMCE as main editor for rich content fields.

To test:
- open the dashboard of a company
- expand a topic
- tap on the topic body: you should see the edit button at the bottom of the viewport (if it has no body the button should appear at the previous step)
- edit the topic: try using the new tinyMCE on mobile too if you like (i didn't test it no android as i don't have my tablet with me but i tested it on the iOS simulator and on my iPhone)
- save (or cancel)
- check that the changes are reflected

### CODE REVIEW

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@bago2k4 once I click "Edit Topic" I just get this error:

http://take.ms/eCWqX

It's still deployed on staging if you want to take a look.

**Comment by bago2k4** [comment]
@belucid should be ok now, i forgot to add tinymce functions to the externs file

**Comment by belucid** [comment]
@bago2k4 Let's hide the "Manage Topic" button when the "Edit Topic" button is shown. When they happen to both be near each other it's weird.

**Comment by belucid** [comment]
@bago2k4 I thought we were trying to get the editor icons into 1 row? I see them as 2 rows of 5.

**Comment by bago2k4** [comment]
@belucid i thought that having only one line was just a fallback for not being able to customize the tinyMCE toolbar in two lines, if we like it better i'll try to adjust it with css and then lose the underline and numbered list features if i can't fit all the buttons

**Comment by bago2k4** [comment]
@belucid this PR should be ready but we should wait to merge until #74 is ready too since this include that branch too

**Pull request merged**
