### PR TITLE
UI/UX Improvements

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/ui9ZxddI

Related PR:
- https://github.com/open-company/open-company-auth/pull/15

To test follow the checklist in the trello card.
Pay particular attention to the password change inserting a wrong current password and the right one. Make sure the save button is enabled only when there is a current password (ie: is not empty) and the new password has at least 5 chars.

### CODE REVIEW

**Comment by bago2k4** [comment]
[Minor UX/UI Improvements (timebox)](https://trello.com/c/ui9ZxddI/800-minor-ux-ui-improvements-timebox)

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@bago2k4 Can you check if this upgrade will work?

https://groups.google.com/forum/#!topic/clojure/cOn8eOgXFsg

**Comment by belucid** [comment]
@bago2k4 is there something incompatible about this branch now w/ the filestack changes in assets package branch?

http://take.ms/g5hwL

**Comment by belucid** [comment]
@bago2k4 style difference between our placeholder text and user text is too slight. Let's lighten up placeholder text some: http://take.ms/LwI54

**Comment by bago2k4** [comment]
@belucid ready to go again if tests don't crash

**Pull request merged**
