### PR TITLE
Ms Edge fixes

### PR DESCRIPTION
**Pull request by bago2k4**
Bug: Microsoft Edge has a [known bug](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15534521/) on scrollTo function, i replaced all those calls with `(set! (.. js/document -scrollingElement -scrollTop) scroll-to-y)` only for this browser.

To test:
- load this branch with Chrome
- scroll down the stream
- click on a post
- [ ] do you see the top of the expanded post without having to scroll back up? Good
- no click the back to AP (or section name) button
- [ ] are you at the same scroll point where you left? Good
- repeat on Edge to make sure it works

### CODE REVIEW

**Comment by bago2k4** [comment]
@cjsauer please take another look, it's fixed for me now..

**Comment by cjsauer** [comment]
@bago2k4 switching sections now results in blank white screen with console errors:

image

**Comment by cjsauer** [comment]
@bago2k4 AP seems to work fine. Other sections are failing to load.

**Comment by bago2k4** [comment]
closing in favor of https://github.com/open-company/open-company-web/pull/943 that is the same list of commits except the big one about `window.document` calls.

**Pull request closed without merging**
