### PR TITLE
Code blocks

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/6MRWcY4W

Related PR:
- [Interaction](https://github.com/open-company/open-company-interaction/pull/43)
- [Lib](https://github.com/open-company/open-company-lib/pull/80)

To test:
- try adding a code block with multiple lines using the picker button
- try adding a code block with multiple lines using the ``` starter
- try adding an inline code using the format button
- try adding an inline code using the ` starter/closer
- make sure you can't format text inside code blocks (both type)
- copy some text that include a `PRE` element from an HTML page and paste it in our editor
- do you see the PRE elements transformed into code?
- do you NOT see text formatted with bold or italic inside etc?
- repeat the copy/paste with a `CODE` element
- test block codes in comments
- make sure digest looks good if there is a post with code blocks
- make sure Slack/email shares looks good if there is a post with code blocks
- make sure notifications (in-app, email, slack) looks good if there are code blocks
- make sure code blocks look good in FoC
- make sure code blocks look good in dark mode

### CODE REVIEW

**Comment by bago2k4** [comment]
[Code blocks (no syntax highlighting)](https://trello.com/c/6MRWcY4W/2252-code-blocks-no-syntax-highlighting)

**Comment by belucid** [comment]
@bago2k4 when I close an inline code block with `single tick` it jumps the cursor back to the start of the line.

**Comment by belucid** [comment]
@bago2k4 The red text for inline code blocks, where did that come from? Is that the design from Ryan? In any case, it's very hard to read in dark mode.

**Comment by belucid** [comment]
@bago2k4 Should code block content be shown FoC?

**Comment by belucid** [comment]
@bago2k4 I do see the formatting pop-up when I highlight text in a multi-line code block

**Comment by belucid** [comment]
@bago2k4 I wonder if the abstract count should be skipping words/chars in a code block. It's odd to see the enter an abstract pop up when I've done nothing but paste in some code.

**Comment by belucid** [comment]
@bago2k4 inline code block font color in dark mode #FFFD93

**Comment by bago2k4** [comment]
@belucid fixed following:
- close with back thick: should be working now
- red text not readable in dark mode: changed to a yellowish color
- hide code in FoC
- formatting popup now should be hidden on FF too

Not fixed:
- remove code blocks from count for abstract: not quick or easy so I skipped it

**Comment by belucid** [comment]
@bago2k4 I still get brought to the front of the line when closing back ticks on FF and Chrome.

**Comment by bago2k4** [comment]
@belucid with a last minute code cleanup I introduced a but that broke my fix.. Now it works, just tested this on staging.

Please make sure the cursor position is correct when you close a code tag with a back thick at the end of a line of text or in the middle of it.

**Pull request merged**
