### PR TITLE
432 feedbacks

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/7ZICygx0

#### Please merge after #120 or merge only this since this is branched from `share-snapshot`

### CODE REVIEW

**Comment by belucid** [comment]
@bago2k4 

- [ ] First edit works fine, but when you make the 2nd edit (no refresh in between) you just get the spinner on the POST button w/ no network request made and no console error.

**Comment by belucid** [comment]
@bago2k4 

- [ ] Expand "Key Challenges" in /open on prod. Click the pencil. Immediately click the X. It warns you about unsaved changes, but you didn't make any.

**Comment by belucid** [comment]
@bago2k4 

- [ ] Expand "Competition" in /open on prod. Click the pencil. Click the body. There is a jump and the body shifts down.

**Comment by bago2k4** [comment]
@belucid can't replicate the dialog problem, tried on all the topics on production for OC, particularly for Key Challenges but none have this problem.. can you try again and tell me if this is still an issue for you?

**Comment by belucid** [comment]
@bago2k4 I'm not seeing it at the moment either. I'll keep an eye out for it in further testing, but for now assume it's not an issue. I deleted the comment.

**Comment by belucid** [comment]
Closed in favor of consolidating to #124.

**Pull request closed without merging**
