### PR TITLE
Settings back

### PR DESCRIPTION
**Pull request by bago2k4**
### Review after #850 

Card: https://trello.com/c/b11GsX4c

To test:
- open menu
- open My Profile
- [x] click Back, did it work?
- click on notifications
- click the X
- [x] back to menu?
- click on recurring updates
- click New
- add a new update
- save
- [x] back to the list of reminders?
- click on the reminder
- click back (or the X)
- [x] back to reminders?
- click back
- [x] back to menu?
- click org settings
- click Back
- [x] back to menu?
- click on invite
- click on X
- [x] back to menu
- click on Integrations
- click Back
- [x] back to menu?
- click on + to add a section
- click back or the X
- [x] back to the stream of posts (menu closed)?
- go to a section
- click on the section settings
- click Back or X
- [x] back to the stream of posts (menu closed)?
- now click on the WRT count of a post
- [x] WRT panel open?
- close it
- [x] did it work?
- open WRT panel again
- from console have a notification: `oc.web.actions.notifications.show_notification(cljs.core.merge(oc.web.lib.utils.app_update_error, clojure.walk.keywordize_keys(cljs.core.js__GT_clj({"id": "test"}))))` (this will show the app update error with the bg color needed by the currently shown panels)
- [x] do you see a light theme notification?

This PR inherited a bug from #850 : the menu doesn't lock the page scroll so you can scroll the page behind the menu panel.

Test inherited issue:
- [x] can you scroll up and down when in All Posts?
- [x] can you scroll up and down when on a section?
- open the menu
- [x] can you NOT scroll the page behind the menu?
- [x] open all the panel accessible from the menu and check the page is still not scrolling
- [x] make sure the panels can scroll if they need: try with a particularly long panel and resize your window
- now open section settings
- [x] can you NOT scroll the page behind?
- now click on the + to add a new section
- [x] can you NOT scroll the page behind?

### CODE REVIEW

**Comment by belucid** [comment]
@bago2k4 this branch fails to run with:

```
The above error occurred in the <notifications> component:
    in notifications (created by app)
    in app

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries. raven.inc.js:58:7
Error: No derivative defined for :expanded-user-menu
```

**Comment by bago2k4** [comment]
hmmm it seems I can't really replicate the error, i tried on Chrome and on FF, on static pages (logged out) and in All Posts and section, no luck.
Did you try rebuilding the app from scratch? Maybe you had some old files that didn't get rebuilt.

**Comment by belucid** [comment]
@bago2k4 design intent was for X to dismiss full panel stack and back to take you back 1.

**Comment by belucid** [comment]
@bago2k4 Let's normalize all the menu items and panel titles to sentence case. In particular these are title case right now:

- My Profile
- Admin Settings
- What's New
- Quickstart Guide
- Sign Out

**Comment by belucid** [comment]
@bago2k4 only "Recurring updates" panel is missing a "Back" to go back to the drop down menu. Seems it should have one too and be consistent with the others.

**Comment by bago2k4** [comment]
@belucid added Back to recurring updates menu

**Comment by belucid** [comment]
@bago2k4 neither "Back" nor X work for Create section panel.

**Comment by bago2k4** [comment]
@belucid good catch, this also made me realise that i was cutting off the private section invite note, i thought we removed that, but we removed only the note for user invites.
So as additional test:
- try adding a new private section with a note and check you receive the invitation with the note
- try the same but creating the section from Cmail (the section creation from Cmail is going away so not very relevant, your call)

**Pull request merged**
