### PR TITLE
Share flow updates

### PR DESCRIPTION
**Pull request by bago2k4**
NB: slack sharing still send the old link for stakeholder updates that doesn't include the SU date

### CODE REVIEW

**Comment by bago2k4** [comment]
[Share flow improvements](https://trello.com/c/Dt5wTYSd/641-share-flow-improvements)

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
- [ ] Update styling of dropdown menu: http://take.ms/iA0j0
- [ ] Update styling of email: http://take.ms/Uykn8

**Comment by bago2k4** [comment]
Here are the updates, @stulev and @belucid i have to say that i don't like the confirmation for slack:
 
screen shot 2016-10-20 at 9 55 58 pm

same goes for email since it uses the same style but it has a done button:

screen shot 2016-10-20 at 9 59 09 pm

What about a title on both?

**Comment by belucid** [comment]
@bago2k4 

- [ ] Add "Email sent!" to the front of the Email confirmation dialog copy
- [ ] Add "Slack message shared!" to the front of the Slack confirmation dialog copy.
- [ ] Remove Done from Email confirmation dialog
- [ ] Have the share button always enabled, and if they are missing a required field (To, Subject) then point it out if they click share (like we do in login forms, etc.)

**Comment by bago2k4** [comment]
@belucid done and deployed to staging

**Pull request closed without merging**
