### PR TITLE
Finances growth polish

### PR DESCRIPTION
**Pull request by bago2k4**
This follows the trello card checklists and the Zeplin sketch (Growth Polish).

### CODE REVIEW

**Comment by bago2k4** [comment]
[Finance and Growth - Polish 0](https://trello.com/c/zHwiTJ7H/688-finance-and-growth-polish-0)

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@bago2k4 

Finances:

- [ ] Give this area a white background: http://take.ms/mJ3ud
- [ ] Don't graph columns that are empty: http://take.ms/UURYt
- [ ] Always show last 4 months of data table in chart when you go into editing. This should be July, August, September, October: http://take.ms/GepZA
- [ ] Runway is not being recalculated on the fly, should be: http://take.ms/mM4Db
- [ ] Chart data doesn't clear out after archiving, it should: http://take.ms/CsxZN

**Comment by belucid** [comment]
@bago2k4 

Growth:

- [ ] Archive chart tooltip copy: "Archive this chart"
- [ ] Give this area white background: http://take.ms/X8mOZ
- [ ] No pillboxes during chart data editing: http://take.ms/3GUEr
- [ ] Always show last 4 months of data table in chart when you go into editing. This should be June, July, August, September: http://take.ms/faVZd
- [ ] Remove transparency from placeholder text so it's easier to read: http://take.ms/SzVYa
- [ ] Placeholder chart copy (notice capitalization, punctuation):
```
Chart will show here with
2 or more periods of data.
```

**Comment by belucid** [comment]
@bago2k4 

We possibly want:

- [ ] No pillboxes during chart data editing: http://take.ms/3GUEr

But hold off on this for now. Might be we need them...

**Comment by belucid** [comment]
@bago2k4 

- [ ] Lots of stuck tooltips on this branch. Just one example, prior next update: http://take.ms/wJrWU

**Comment by belucid** [comment]
@bago2k4 needs a conflict merge

**Pull request closed without merging**
