### PR TITLE
Marketing site updates

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/dpJpVFIV

This also addresses the MS browsers problems.
The emoji picker is disabled on IE11 for now since it's not working and not worth spending time on fixing it since we are going to replace that.

### CODE REVIEW

**Comment by bago2k4** [comment]
[Marketing site updates; footer links](https://trello.com/c/dpJpVFIV/1046-marketing-site-updates-footer-links)

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
I get this locally on a complete refresh:

http://take.ms/TrWFw

**Comment by bago2k4** [comment]
@belucid i was trying to reproduce this but i couldn't. Can you provide me steps to do it.
Did you restart boot after checking out this branch?

**Pull request merged**
