### PR TITLE
Stories

### PR DESCRIPTION
**Pull request by bago2k4**
Trello card: https://trello.com/c/kHqOZct2

### CODE REVIEW

**Comment by bago2k4** [comment]
[Copy changes](https://trello.com/c/HgqugTtD/984-copy-changes)

**Comment by belucid** [comment]
@bago2k4 Results of some QA:

- [ ]  http://take.ms/uuHNB Sequence, started w/ new update, added comment with the text "Test comment #" 1 by 1 until I got to the 7th, at which point the UI gliched.
- [ ] Open a new update. Add a comment. Add a 2nd comment. Close the update to go back to the board. Notice the board says "1 comment" rather than 2.

**Comment by bago2k4** [comment]
[Stories](https://trello.com/c/kHqOZct2/828-stories)

**Comment by bago2k4** [comment]
Closing and moving the remaining issue to `iu-ux-polish` PR.

**Pull request closed without merging**
