### PR TITLE
Polls

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/EBOzBTjn/2359-polls

Related PRs:
- [Storage](https://github.com/open-company/open-company-storage/pull/243)
- ~~[Infra](https://github.com/belucid/open-company-infrastructure/pull/128)~~

To test:
- add a poll
- vote a poll
- vote with other users to a poll
- add multiple polls to the same post
- make sure tabbing btw choices work when there are multiple polls
- make sure you can always add some text above and below a poll: add it as first thing, after you typed something, after you added an image or video
- make sure you can always add some text above and below a poll: try editing a post previously saved with a poll at the top or bottom
- checkout polls on mobile (read and edit)

### CODE REVIEW

**Comment by bago2k4** [comment]
[Polls](https://trello.com/c/EBOzBTjn/2359-polls)

**Comment by belucid** [comment]
@bago2k4 when you click to Add an option, the added option ought to get the keyboard focus.

**Comment by belucid** [comment]
@bago2k4 If I add an option but never put anything in it, it hangs around as a blank option. A blank option should just go away.

**Comment by belucid** [comment]
@bago2k4 I'm still seeing options change order. Sequence:

- Edit a post.
- Add a poll with 4 options
- Save the post
- Immediately vote for the 2nd option
- Notice it jumps up to be the 1st option

**Comment by belucid** [comment]
@bago2k4 tabbing from the last option in edit mode ought to create an additional option

**Comment by belucid** [comment]
@bago2k4 just one decimal place is enough precision

**Comment by bago2k4** [comment]
@belucid with a last minute code cleanup I introduced a but that broke my fix.. Now it works, just tested this on staging.

Please make sure the cursor position is correct when you close a code tag with a back thick at the end of a line of text or in the middle of it.

**Comment by belucid** [comment]
@bago2k4 merge conflicts here now

**Pull request merged**
