### PR TITLE
Fullscreen post

### PR DESCRIPTION
**Pull request by bago2k4**
Card:
- https://trello.com/c/qqBNTxsL
- https://trello.com/c/DJo0GTip
- https://trello.com/c/gdY3IQwe

The above are all connected because of the `stream-comments` component used in `fullscreen-post` and in `all-post` components.

### CODE REVIEW

**Comment by bago2k4** [comment]
[Jelly UX: Full screen post](https://trello.com/c/qqBNTxsL/1185-jelly-ux-full-screen-post)

**Comment by bago2k4** [comment]
[Move comment box to the top](https://trello.com/c/gdY3IQwe/1196-move-comment-box-to-the-top)

**Comment by thepug** [comment]
@bago2k4 label this as ready to review?

**Comment by bago2k4** [comment]
[Fix AP position on small screens](https://trello.com/c/DJo0GTip/1209-fix-ap-position-on-small-screens)

**Comment by bago2k4** [comment]
@belucid @thepug I marked this as URGENT because there are 2 PRs already that are branched from this so it's critical to unlock all our work to review and merge this.

**Pull request merged**
