### PR TITLE
WST updates

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/kKLd6m1M

### Which in turn needs: https://github.com/open-company/open-company-lib/pull/65

To test:
- create a new private section
- add a few users to it (but not all)
- now add a post to the new priv section
- open WST for the post
- [x] do you see only the users invited to the private section in the list?
- [x] only the users that didn't read the post have the Notify button?
- [x] do you see a Manage section green button below the chart copy?
- click it
- [x] did it open the section management panel?
- now read a post with all the users
- [x] do you see a different copy below the chart (not saying how many users have read out of how many, check the Trello card for the exact copy)
- [x] make sure the style linked in the card is implemented
- now click Notify button for an email user
- [x] do you see the copy change to `Sent to: email-of-user@domain.com`?
- now click Notify button besides a Slack user
- [ ] do you see the copy change to `Sent to: @slack-username` (if we don't have a display name for the user it will say only `Sent via Slack`?
- now add a new post with user A
- with user B don't open it but add a reaction from FoC
- refresh
- [x] post is still unread for user B?

UI checks that user has Slack, and Org w/ the bot

### CODE REVIEW

**Comment by bago2k4** [comment]
[WST updates](https://trello.com/c/kKLd6m1M/2023-wst-updates)

**Comment by belucid** [comment]
@bago2k4 a couple of feedback items in the Trello card

**Comment by bago2k4** [comment]
@belucid addressed Trello feedback

**Comment by belucid** [comment]
Awaiting PR https://github.com/open-company/open-company-storage/pull/196 for further review.

**Comment by belucid** [comment]
@bago2k4 I have 3 people in my private section. But WST only shows 2. The one not shown is a viewer for the section.

**Comment by belucid** [comment]
@bago2k4 also merge issue now.

**Comment by bago2k4** [comment]
@belucid should be good now

**Comment by belucid** [comment]
@bago2k4 conflicts here now

**Comment by bago2k4** [comment]
@belucid pushed conflicts fix... this seems to be the last PR 🎉 🎉 🎉 🎉

**Comment by belucid** [comment]
@bago2k4 the private filtering breaks the everyone has seen it logic.

E.g. My org has 4 users, only 3 of which are in a private section. When 3 of 3 have read the post in the private section, I still get the 3 of 3 copy rather than the everyone copy.

https://take.ms/No80d4

**Comment by belucid** [comment]
@bago2k4 I just get "sent to:" but no email address when I send to the email user

**Comment by belucid** [comment]
@bago2k4 `403` response to the share when sending to a Slack user from WST

**Comment by belucid** [comment]
@bago2k4 revalidated all the fixes. Only remaining issue on the PR that I see is the 403.

**Pull request merged**
