### PR TITLE
Chart animation

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/fYnU2FQm

to test:
- load buffer
- scroll down the page
- watch the charts animate when they come into view
- load new.ly to make sure that the charts are animated also when they are already visible on page load (no scrolling happens)
- merge

### CODE REVIEW

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
Switching between metrics in growth doesn't do anything with the chart on this branch.

**Comment by belucid** [comment]
@bago2k4 on finances there's a noticeable delay when switching between the links. It isn't there on mainline. Can this delay be removed?

**Comment by bago2k4** [comment]
@belucid checking now

**Comment by bago2k4** [comment]
@belucid animations look good to me now. I checked: first appearance (the chart is already visible when the page load), first appearance after scrolling the page, transition between growth metrics and finances links, transitions between revisions

**Pull request merged**
