### PR TITLE
Chart tweaks 3

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/hrUDr6WC

test:
- check from the card checklists

### CODE REVIEW

**Comment by bago2k4** [comment]
@belucid this is good again, i checked all our test companies and i think all the charts are fixed now.

**Comment by belucid** [comment]
@bago2k4 please merge mainline in.

**Comment by belucid** [comment]
Reviewing.

**Comment by bago2k4** [comment]
@belucid wait for CI than this is good to go

**Comment by belucid** [comment]
@bago2k4 WARNING: Wrong number of args (1) passed to open-company-web.lib.utils/calc-runway at line 124 src/open_company_web/components/finances/finances_edit.cljs

**Comment by belucid** [comment]
@bago2k4 please merge mainline in again.

**Pull request merged**
