### PR TITLE
Media handling

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/sVzZQCRd

Related PRs:
- proxy: https://github.com/open-company/open-company-proxy/pull/1
- lib: https://github.com/open-company/open-company-lib/pull/16

### CODE REVIEW

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@bago2k4 

- Video placeholder is used when adding a chart: http://take.ms/FA299
- If you cancel the image, chart, or video add, then the (+) is borked a bit. You have to give the field focus again for it to work, but the (+) is there to be clicked on, so people won't necessarily do that. 
Probably the (+) should be there visible after cancel.
- If you go to a newline when the body placeholder is showing (enter or down arrow) the placeholder stays there, it shouldn't)

**Comment by bago2k4** [comment]
@belucid issues addressed

**Comment by belucid** [comment]
@bago2k4 tests are failing

**Comment by bago2k4** [comment]
@belucid hmmm you sure about tests?

**Comment by bago2k4** [comment]
@belucid oh i see, you meant the proxy tests. ok checking now

**Comment by belucid** [comment]
Reviewing again.

**Comment by belucid** [comment]
@bago2k4 

- [ ] emoji picker from : isn't working properly, emoji is half cut off https://www.useloom.com/share/0c18aafaa48f4ecc9293cf356df6ef9e
- [ ] first media isn't showing FoC when there is more than 1 https://www.useloom.com/share/c3b8f2636f8f43149b53363cd54f017d

**Comment by belucid** [comment]
@bago2k4 

- [ ] There is still an issue with canceling an image add https://www.useloom.com/share/7a8582583f6f424fbe184dd9d0587c5b

**Comment by bago2k4** [comment]
@belucid all issues should be addressed. I added also an error state as discussed in Slack. Ping me if you want to see it in action.

**Comment by belucid** [comment]
@bago2k4 

If you only have media (in this case a video) and nothing else, and you save and then edit the entry, it shows the placeholder overlayed with the media. It shouldn't:

http://take.ms/Pt3Lb

**Comment by belucid** [comment]
@bago2k4 we must not be putting together the thumbnail image requests for Vimeo properly. The image we get back seems random and never has anything to do with the video.

**Comment by belucid** [comment]
@bago2k4 after I add a Vimeo video the `data-video-type` attribute is set to `youtube`.

**Comment by bago2k4** [comment]
@belucid fixed. I think this is not related but i'll explain just the same so you can test to make sure.
I'm using `stories` storage branch. when i create a new entry the POST fails because `:ERR_RESPONSE_HEADERS_TOO_BIG`. check Slack for more details

**Comment by belucid** [comment]
@bago2k4 

- [ ] Can't add attachments in this branch, get an error when you click: http://take.ms/l1syX

**Comment by bago2k4** [comment]
@belucid attachments were fixed yesterday, i forgot to tell you

**Comment by belucid** [comment]
@bago2k4 

- [ ] If you edit a shorter update to have more content (so to be longer) then click save, when the non-editable modal comes back the comment sidebar is too short: http://take.ms/ZSqoN

**Pull request merged**
