### PR TITLE
Linked charts

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/ZWMu5BHt

Related PRs:
- [lib](https://github.com/open-company/open-company-lib/pull/7)
- [proxy](https://github.com/open-company/open-company-proxy): no PR, but mainline review mainline code
- [infrastructure](https://github.com/belucid/open-company-infrastructure/pull/37)

To test:
- add a chart using the new UI
- save and check that the chart is rendered as expected
- go back to the google sheet and update the chart
- check that the chart doesn't change on our side
- edit the topic and click the refresh button
- check that the chart is updated now
- now if you click SAVE the new chart should be kept, if you CANCEL the old one should re-appear (at least until the cache doesn't expire)
- remove the chart and save
- if everything is working as expected merge!

### CODE REVIEW

**Comment by bago2k4** [comment]
[Charts from Google Sheets](https://trello.com/c/ZWMu5BHt/810-charts-from-google-sheets)

**Comment by belucid** [comment]
Reviewing

**Comment by belucid** [comment]
@bago2k4 

Seems that even though we're not showing the legend, the space for the legend is being reserved and not used for the chart, so the charts are still as narrow as they were w/ the legend.

**Comment by belucid** [comment]
@bago2k4 

Match the Chart URL styling to the company name text box styling. 14px, 1.2 line height, 8px left/right pad, etc.

**Comment by belucid** [comment]
@bago2k4 

Adding emoji to entry body with the picker is not working.

oc.js:42 Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': Only one element on document allowed.

**Comment by belucid** [comment]
@bago2k4 

Adding an image or file, get the following 401's on 4 filestack resources:


oc.js:42 GET https://cloud.filestackapi.com/googledrive/folder/list?apikey=Aoay0qXUSOyVIcDvls4Egz 401 (Unauthorized)
(anonymous) @ oc.js:42
A._end @ filestack-0.1.10.js:2
A.end @ filestack-0.1.10.js:2
(anonymous) @ filestack-0.1.10.js:4
r @ filestack-0.1.10.js:4
o @ cloud.js:146
i @ Bottleneck.js:238
(anonymous) @ Bottleneck.js:178
d @ oc.js:42
oc.js:42 GET https://cloud.filestackapi.com/onedrive/folder/list?apikey=Aoay0qXUSOyVIcDvls4Egz 401 (Unauthorized)
(anonymous) @ oc.js:42
A._end @ filestack-0.1.10.js:2
A.end @ filestack-0.1.10.js:2
(anonymous) @ filestack-0.1.10.js:4
r @ filestack-0.1.10.js:4
o @ cloud.js:146
i @ Bottleneck.js:238
(anonymous) @ Bottleneck.js:178
d @ oc.js:42
oc.js:42 GET https://cloud.filestackapi.com/box/folder/list?apikey=Aoay0qXUSOyVIcDvls4Egz 401 (Unauthorized)
(anonymous) @ oc.js:42
A._end @ filestack-0.1.10.js:2
A.end @ filestack-0.1.10.js:2
(anonymous) @ filestack-0.1.10.js:4
r @ filestack-0.1.10.js:4
o @ cloud.js:146
i @ Bottleneck.js:238
(anonymous) @ Bottleneck.js:178
d @ oc.js:42
oc.js:42 GET https://cloud.filestackapi.com/dropbox/folder/list?apikey=Aoay0qXUSOyVIcDvls4Egz 401 (Unauthorized)

**Comment by bago2k4** [comment]
@belucid those 401 are always shown from filestack until you grant permissions to the particular service. I have always seen them in the console. i was able to remove one only adding a file using that particular service. Solving the rest now

**Comment by belucid** [comment]
Got it on the 401's @bago2k4

**Comment by bago2k4** [comment]
@belucid i fixed all the remaining problems, emoji-picker was broken because i was removing the markers (used to remember where the user want to insert the emoji) too soon.
Also i upgraded Raven in cljsjs so we need to wait for this [PR](https://github.com/cljsjs/packages/pull/1147) to be merged, usually they are pretty fast but we can always install the package locally if we need to deploy this (this was already done on staging).

**Comment by bago2k4** [comment]
@belucid travis is failing because it's not finding raven-3.14.2, tests are passing locally so they should also here but if you want to make sure we need to wait for cljsjs to merge the PR i linked in the last comment.

**Comment by bago2k4** [comment]
@belucid raven-3.14.2 has been merged and published on clojars. I'm restarting CI here to make sure it works now.

**Pull request merged**
