### PR TITLE
Big web

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/gpApBZ9G

NB: some of the style details has yet to be defined as per the [design feedbacks doc](https://docs.google.com/document/d/1c61v8mkPEjEbDDsWoChjnHRjbSHSvoHGmSQbeGObZYg/edit) so try not to be too sharp.
The type of layout is chosen checking the window width, until 970px is considered mobile, above it it's big web, for now this doesn't take into account the browser's user agent and there is no distinction between smartphones and tablets.

To test:
- check the mock for big web
- try to expand/collapse some topics
- the topic expand animation has to be improved yet: i'm waiting for some feedback on the current one
- expand a topic then click on another topic in the same row: there is no animation for this yet, i'll work on it when i have some feedback on the current expand animation and maybe some guidelines
- check that this doesn't break anything on mobile (activate the chrome device mode or check this on your device)

### CODE REVIEW

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@bago2k4 logo in top left (nav bar) should be opencompany logo, not the company's.

Use: https://open-company-assets.s3.amazonaws.com/open-company.png

**Comment by belucid** [comment]
@bago2k4 we still have Lora/Arial as fonts. John's designs use Proxima Nova.

**Comment by belucid** [comment]
@bago2k4 While the page is loading I see the "ALL" category.

**Comment by belucid** [comment]
@bago2k4 there is some shadowing on the right and bottom of the cards that's missing.

**Comment by belucid** [comment]
@bago2k4 Just 1 bg grey: http://take.ms/TQ9Cc

**Comment by belucid** [comment]
@bago2k4 design cards are 290px wide, ours are 270px.

**Comment by belucid** [comment]
@bago2k4 we'll need some hover treatment for cards to make them feel more alive. See #design channel for some input from John.

**Comment by belucid** [comment]
@bago2k4 Design has company name and description to the right of the company logo, not below it.

**Comment by belucid** [comment]
@bago2k4 let's do the same previous / next transition we do on the old big web design

**Comment by belucid** [comment]
@bago2k4 no "Last updated by ".

Just "Joel Gascoigne on November 20"

**Comment by belucid** [comment]
@bago2k4 Manage Topics shouldn't have an "ALL"

**Comment by belucid** [comment]
@bago2k4 can't save / cancel on manage topics on big web

**Comment by belucid** [comment]
@bago2k4 click to "ALL", then resize window to mobile, You still see all the content but w/ nothing selected. Should revert to progress and show only progress content and rewrite the URL. (I know I told you to ignore the sizing down case, but this is more important for an ALL URL getting shared to a mobile user, than for resizing).

**Comment by bago2k4** [comment]
@belucid ready again, when you want.

**Comment by belucid** [comment]
Awesome @bago2k4 , I'll take a look shortly.

**Comment by belucid** [comment]
@bago2k4 company name and logo on the right needs to adjust for logo size: http://take.ms/N2Szr

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@bago2k4 Valdis suggested CSS Red for Cancel link and CSS Green for Save link in Manage Topics, so they are less likely to be missed.

**Comment by belucid** [comment]
@bago2k4 Expand a topic, then navigate to another category. The topic stays there expanded. It should go away.

**Comment by belucid** [comment]
@bago2k4 make the expand/collapse animation slightly shorter, feels just a tad sluggish.

**Comment by belucid** [comment]
@bago2k4 Logged in, on a r/w company, but I can't edit.

**Comment by belucid** [comment]
@bago2k4 border separating top nav from company description is too dark. Border above and below category filter is too dark.

**Comment by belucid** [comment]
@bago2k4 padding around category filter should be 10px (currently 5) which sets the length of the dark border below the active category.

**Comment by belucid** [comment]
@bago2k4 Fade unselected topic cards by 50% when any topic card is expanded

**Comment by bago2k4** [comment]
@belucid all the above addressed apart the animation fixes for topic expand: switching topic on the same row and to another on another row. i'll fix those asap, not sure it will be today though.

**Pull request merged**
