### PR TITLE
Ui punchlist

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/ZEjghgDn

### CODE REVIEW

**Comment by bago2k4** [comment]
[UI Punchlist](https://trello.com/c/ZEjghgDn/753-ui-punchlist)

**Comment by bago2k4** [comment]
@belucid this should be good to be reviewed now.

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@bago2k4 

- [ ] Let's address these style issues here in this UI PR: http://take.ms/fQMtIW

**Comment by belucid** [comment]
@bago2k4 

- [ ] check if it'll fit and if not, center it with no arrow pointer thingy instead http://take.ms/4Bahm

**Comment by belucid** [comment]
@bago2k4 all done. Looks good except for 2 issues above.

**Comment by belucid** [comment]
@bago2k4 

http://take.ms/pe5YG

**Pull request merged**
