### PR TITLE
Foc collapsed view

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/fVmCSLpC

To test TBD

NB: test case where user is loading FoC in collapsed mode with a very high window that fits more than 1 page and make sure all the possible pages are loaded and also the auto load more still works.

### CODE REVIEW

**Comment by bago2k4** [comment]
[FoC collapsed style](https://trello.com/c/fVmCSLpC/2371-foc-collapsed-style)

**Comment by belucid** [comment]
@bago2k4 conflicts on this one.

**Comment by belucid** [comment]
@bago2k4 funkiness when hovering over collapsed posts

**Comment by bago2k4** [comment]
@belucid this should be good now (CI permitting)

**Pull request merged**
