### PR TITLE
Dashboard/SU manage

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/7FL3PxMB

___

Review with this: https://github.com/open-company/open-company-api/pull/38
___

NB: This branch has changes from all of us: it's based on sean's su branch and it contains martin's [361-svg-image-issues](https://github.com/open-company/open-company-web/pull/93). Same goes for the API PR.

You need to reimport all the sample data to add the :icon key to the sections.

To test follow the card description. Also try to quickly click the active/unactive topics to see how the ui reacts.

### CODE REVIEW

**Comment by belucid** [comment]
@bago2k4 please merge in mainline

**Comment by belucid** [comment]
Reviewing

**Comment by belucid** [comment]
- [ ] Every other time you expand collapse, you end up with a + on an expanded drawer, or an X on a closed drawer (just repeatedly expand and collapse to see this)

**Comment by bago2k4** [comment]
@belucid all done

**Comment by belucid** [comment]
@bago2k4 this is almost ready, just 1 bit:

- [ ] Make the entire thing (except the checkbox) a DnD draggable, not just the handle. Only have clicking the checkbox change the active/inactive, not clicking the rest of the card.

**Comment by bago2k4** [comment]
@belucid all done

**Pull request merged**
