### PR TITLE
Fast copy changes

### PR DESCRIPTION
**Pull request by bago2k4**
From [QA doc](https://paper.dropbox.com/doc/Post-beta-bugs-and-comments--AeKTdIEUmhMgJAbXXPP6Rxz7Ag-SPQWk76sbpqMUySRddhEm)

Items:
- [x] When post, go to stream.. not the full page view
- [x] Change “Reminders” to say “Recurring update reminders” (in the notification settings screen)
- [x] Change tooltip copy for the quick summary (preview text + NUX tooltip)
- [x] Active section label should be bold
- [x] For fields with in-line validation, please use a single px stroke of Carrot green for positive, and Carrot orange for negative
- [x] Replace the company drop down arrow with the double deep navy drop down icon
- [x] Mobile only: increase blue bar width on the must see unread state from 2px to 4px
- [x] When you delete the sample post, it still asks you if you want to “Delete all samples posts?” but there’s only one. Don’t need to ask that anymore.
- [x] In the Advanced Settings, the “i” for information tip feels broken because I click on it and nothing happens. The tip appears on hover, but it takes too long, so it feels broken. Either make it work on click, or very fast on hover.
- [x] Image controls, and attachments are too close to the bottom of the desktop window; need to always have some padding there. 
- [x] Add “(private)” or “(public)” to behind the section name  on FoC and when viewing a full-screen post 
- [x] Ensure these buttons are the same color
- [x] Empty state is needed for recurring updates screen
- [x] A viewer user gets no … ellipse FoC for read/unread management
- [x] Mobile: Padding on the post creation doesn’t match the header area to the body area
- [x] Mobile: The preview texts are different colors, both should be deep navy @ 50%
- [x] When clicking “Add a comment” on FoC, the user should be taken to the comment section of a post and have the comment input box activated so they can start typing
- [x] Remove the URL entirely in settings
- [x] User hover information breaks when the email is long
- [x] Preserve scroll position after you open/close a post
- [x] Remove animation when opening a post
- [x] If I click the number of comments on FoC, then take the user to the add comment box
- [x] If click a link on FoC, don’t open the post (just follow link)
- [x] Shortcut: Cmd + enter should allow a user to “post” their post (just like how it works with posting a comment)

### CODE REVIEW

**Comment by belucid** [comment]
@bago2k4 ready or WIP?

**Comment by bago2k4** [comment]
ops sorry for the ambiguity @belucid , it's ready but i didn't remove the WIP since i wanted to re-check with the QA doc if there are any items left.
I guess you can review this and if there are more i'll do another PR

**Comment by bago2k4** [comment]
@belucid removing the label once more, i'll add the last remaining fast items here

**Comment by bago2k4** [comment]
[2.0 Launch QA feedback](https://trello.com/c/zDSujYvW/2057-20-launch-qa-feedback)

**Comment by belucid** [comment]
@bago2k4 conflicts here.

**Comment by bago2k4** [comment]
@belucid fixed here too

**Comment by belucid** [comment]
@bago2k4 conflict here again.

**Comment by bago2k4** [comment]
@belucid fixed conflicts and also pushed a fix for the scroll adjustment when opening and closing a post from the stream.
This probably will need more testing after #911 is merged

**Comment by belucid** [comment]
@bago2k4 conflicts here.

**Comment by belucid** [comment]
@bago2k4 

"When post, go to stream.. not the full page view"
I end up at the full page view

When testing the orange/green outline stroke, I ran into this:
- go to admin settings
- clear out your company name
- click save
- get error, that's good
- type in a name again
- error stays, save button never enables, not good


I'm not sure what buttons this refers to: "Ensure these buttons are the same color"

I'm not sure where this is referring to: "User hover information breaks when the email is long"

**Pull request merged**
