### PR TITLE
Input fields opacity

### PR DESCRIPTION
**Pull request by bago2k4**
From  [paper feedback doc](https://paper.dropbox.com/doc/QA-tests--Ad4kXGKrmm6V~FQi70mgAgNAAg-SPQWk76sbpqMUySRddhEm)

Item:
> When a field input or dropdown becomes active, please lower opacity by 10% so that there is a state change

To test:
- [x] check opacity is applied to input fields of the signup flow
- [x] check opacity is applied to input fields of the login flow
- [x] check opacity is applied to input and select fields (not only native selects fields) in the org settings panels
- [x] check opacity is applied to input and select fields in the user settings panels
- [ ] check opacity is applied to input and select fields in recurring updates
- [ ] check opacity is applied to input and select fields in section editing
- [x] check that Cmail (and Bmail) is not affected by this change

### CODE REVIEW

**Comment by belucid** [comment]
@bago2k4 kibit failure on this one.

**Comment by bago2k4** [comment]
Thanks @belucid and Kibit. Fixed

**Comment by belucid** [comment]
@bago2k4 odd coloring here: https://take.ms/J0a3f

Title is the focused field so why are "Assign to" and "Every" light while "On" is dark?

**Comment by belucid** [comment]
@bago2k4 no opacity when section name or personal note is selected in section dialog

**Comment by bago2k4** [comment]
@belucid fixed

**Comment by belucid** [comment]
@bago2k4 some conflicts here.

**Pull request merged**
