### PR TITLE
Video image instead of player to improve performance.

### PR DESCRIPTION
**Pull request by thepug**
Load an image and our own spinner instead of the ziggeo player so that mobile devices perform better.

Needs https://github.com/open-company/open-company-storage/pull/155

To test:

- create a few video posts
- and reload all posts with a few of the videos displayed.
- [x] do you see the video image with a play button?
- [x] is it an image and not the ziggeo player (inspect the html for the img tag)
- [x] can you click the image to play the video?

- create a video post
- [x] does the ziggeo player load after posting instead of displaying the img?

- open a display of all posts with a second user
- create a video post as the first user
- [ ] as the second user do you see the new post with a spinner?

### CODE REVIEW

**Comment by thepug** [comment]
[Mobile performance](https://trello.com/c/v42HKKEe/1526-mobile-performance)

**Comment by bago2k4** [comment]
@thepug one quick feedback: the cover image with the play button should have the pointer hand instead of the default mouse cursor.

**Comment by thepug** [comment]
@bago2k4  updated

@thepug one quick feedback: the cover image with the play button should have the pointer hand instead of the default mouse cursor.

**Comment by thepug** [comment]
found an issue 
screenshot

**Comment by bago2k4** [comment]
Also @thepug not sure this is related but your front video image is looking good:
screenshot_20181009-163449
but when i click it the video player is not wide enough (see the white band on the right)
screenshot_20181009-163455

This video is on staging, you can check it yourself: https://staging.carrot.io/carrot/apseen2/post/26de-4c9d-8ca7

**Comment by bago2k4** [comment]
@thepug i don’t see this
>  as the second user do you see the new post with a spinner?
steps:
- user B watching AP
- record video as user A
- upload video
- publish as user A
- user B sees post comes in but w/o video
- user B eventually sees the video appear (with our fake cover shot but no spinner)

**Pull request merged**
