### PR TITLE
Project repl

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/cixNtXvn

Follow the steps in the README to start and connect to a clojurescript REPL via browser.

Thanks @martinklepsch for help. If you have the time take a minute to review my configuration.

### CODE REVIEW

**Comment by martinklepsch** [comment]
Looks good to me 👍

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@bago2k4 

Following the README directions, I get this when I run `boot repl -c`:

```
clojure.lang.ExceptionInfo: Assert failed: host and/or port not specified for REPL client
                            (and h p)
    data: {:file
           "/var/folders/jc/p0flb9dx5x3bck7thdb0wfxr0000gn/T/boot.user1857071135213381510.clj",
           :line 33}
  java.lang.AssertionError: Assert failed: host and/or port not specified for REPL client
                            (and h p)
            boot.repl-client/client  repl_client.clj:   10
                                ...
                 clojure.core/apply         core.clj:  630
              boot.pod/eval-fn-call          pod.clj:  328
                  boot.pod/call-in*          pod.clj:  379
                                ...
                  boot.pod/call-in*          pod.clj:  382
        boot.task.built-in/fn/fn/fn     built_in.clj:  393
                                ...
                 clojure.core/deref         core.clj: 2206
     boot.task.built-in/fn/fn/fn/fn     built_in.clj:  397
     boot.task.built-in/fn/fn/fn/fn     built_in.clj:  394
                boot.core/run-tasks         core.clj:  938
                  boot.core/boot/fn         core.clj:  948
clojure.core/binding-conveyor-fn/fn         core.clj: 1916
                                ...
```

**Comment by bago2k4** [comment]
@belucid looks like your issue is similar to this: https://github.com/adzerk-oss/boot-cljs-repl/issues/27

are you sure you started a repl server with `boot dev` before trying to start a client with `boot repl -c`?
looking at the failing tests now

**Pull request merged**
