### PR TITLE
Safari fixes

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/lpjVt3jW

NB: for the font fix i need to wait until we have a license for the Circular web font and we can add it to the page load.

To test follow the items in the trello card.

### CODE REVIEW

**Comment by bago2k4** [comment]
[Safari issues](https://trello.com/c/lpjVt3jW/2052-safari-issues)

**Comment by belucid** [comment]
@bago2k4 Must See badge is funky.

**Comment by belucid** [comment]
@bago2k4 badge still funky on CMail https://take.ms/tcWMY

**Comment by bago2k4** [comment]
@belucid fixed

**Pull request merged**
