### PR TITLE
Return of FoCE

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/ZNRFIOF7

### CODE REVIEW

**Comment by bago2k4** [comment]
[Return of the "in place" FoCE](https://trello.com/c/ZNRFIOF7/762-return-of-the-in-place-foce)

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@bago2k4 This mostly looks great.

1 big issue. The FoCE edit (as opposed to new entry) is using the `update`/PUT (creates a new revision) rather than `partial-update` which edits.

I'll resolve lack of the link on the API side.

**Comment by belucid** [comment]
@bago2k4 

- [ ] Use Fundraising and Finances in a company, and the header doesn't appear in the list (great!) but it leaves a gap (not good) http://take.ms/4JETi

**Comment by belucid** [comment]
@bago2k4 

- [ ] missing 3rd "point to the little +" tooltip

**Pull request merged**
