### PR TITLE
Copy changes

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/6TpkaWsD

Copy docs:
Web: https://docs.google.com/document/d/142Lp4a_LIrg3HvmSvHT2U3KxvC7edolOyYZih7aM4HQ/edit
NUX: https://docs.google.com/document/d/1-Vhh0H2onNaa981u3rcvAfnbcu0MMYiTFGww6ruMT8Q/edit

### CODE REVIEW

**Comment by belucid** [comment]
@bago2k4 

This one is checked off: Footer - if someone is signed in but closed the window and comes back, don’t show “Your boards” link in the footer

But I still see the link in the footer.

**Comment by belucid** [comment]
@bago2k4 there's some new notes in from Stuart in at the top of the lander GDoc that we probably want in this PR.

**Comment by belucid** [comment]
@bago2k4 NUX all looks good.

**Comment by bago2k4** [comment]
@belucid latest copy changes and style fixes are in (check the QA doc for details).

**Pull request merged**
