### PR TITLE
improve "access denied" page

### PR DESCRIPTION
**Pull request by martinklepsch**
[trello card](https://trello.com/c/0E4bRjHX/470-logged-in-but-not-to-that-company)

**To Test**

- [x] login with test org
- [x] go to /bago, you should see two lines of text explaining you don't have access but you can change slack orgs
- [x] switch accounts via the link, OC org this time
- [x] you should be redirected to /bago after successful signin

### CODE REVIEW

**Comment by belucid** [comment]
@martinklepsch is this ready? It's not assigned, but it's in PR lane in Trello (w/ no PR link). So, I'm not sure.

**Comment by martinklepsch** [comment]
@belucid sorry, missed it! This is ready, yes.

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@martinklepsch 

This branch fails deploying to staging with:

```
TASK [OC Web | Upload source map to Sentry] ************************************
fatal: [52.20.90.4]: FAILED! => {"changed": true, "cmd": "curl https://app.getsentry.com/api/0/projects/opencompany/oc-staging-web/releases/1465074534/files/ -u 6d9adb27b8c84afb9790f955779631a2: -X POST -F file=@target/public/js/oc.js.map -F name=\"https://staging.opencompany.com/js/oc.js.map\"", "delta": "0:00:00.121476", "end": "2016-06-04 21:10:23.715724", "failed": true, "rc": 26, "start": "2016-06-04 21:10:23.594248", "stderr": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\ncurl: (26) couldn't open file \"target/public/js/oc.js.map\"", "stdout": "", "stdout_lines": [], "warnings": ["Consider using get_url module rather than running curl"]}
```

**Comment by martinklepsch** [comment]
Ugh, issue was using two `_` in (seemingly) unrelated argvecs:
```clojure
(defcomponent login-button [{:keys [auth-settings]} _]
  (render [_]
    (dom/button {:class "login-button" :on-click #(login! (:auth-url auth-settings) %)}
      "Sign in / Sign up")))
```

**Comment by martinklepsch** [comment]
@belucid resolved

**Comment by bago2k4** [comment]
@martinklepsch yeah i found this issue already some times ago. it's strange because using the same name for 2 args in those places results in error only when you build for production, locally it works and the var gets overwritten.

**Comment by martinklepsch** [comment]
@bago2k4 probably because locally we don't pipe stuff through Closure compiler and the Closure compiler is a bit more strict about stuff

**Comment by belucid** [comment]
@bago2k4 please finish this review

**Comment by bago2k4** [comment]
reviewing

**Pull request merged**
