### PR TITLE
Share snapshot

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/Mydf6By1

Placeholder to collect feedbacks

### CODE REVIEW

**Comment by belucid** [comment]
- [ ] Can't add a topic on this branch. Gets a cljs error.

**Comment by bago2k4** [comment]
@belucid should be all addressed

**Comment by belucid** [comment]
@bago2k4 the add topic dropdown popup opening upward when it's at the bottom of the view isn't happening in this branch.

**Comment by belucid** [comment]
@bago2k4 a couple from iPad (mobile Safari):

- [ ] Avatar is cut off
- [ ] Share snapshot is shone, shouldn't be

**Comment by belucid** [comment]
@bago2k4 After archiving a topic, it is left me on a blank page with the “X” top right rather than back to the dashboard

**Comment by belucid** [comment]
@bago2k4 

- [ ] Feedback on SHARE URL sub-dialog: http://take.ms/78QRL
- [ ] CANCEL on share dialog should be in a box (see mock)

**Comment by belucid** [comment]
@bago2k4 

- [ ] URL box in URL share sub dialog should be 50% wider than it is
- [ ] URL box and COPY button are 50px tall, the PREVIEW AND SHARE button is 30px tall. The URL text/button should be 30px.

**Comment by belucid** [comment]
- [ ] Final Share dialog cleanup http://take.ms/S9A0Z
- [ ] Change Slack share text from "YOUR SNAPSHOT WILL BE SHARED WITH ALL THE MEMBERS OF YOUR SLACK ORGANIZATION" to "SHARE SNAPSHOT WITH THE MEMBERS OF YOUR SLACK ORGANIZATION". Size the dialog so it fits on 2 lines if it doesn't.

**Comment by bago2k4** [comment]
@belucid should be good now

**Comment by belucid** [comment]
@bago2k4 the snapshot preview isn't responsive, if you start at 3 columns it's staying there. Should go to 2 columns.

**Comment by belucid** [comment]
Closing in favor of more recent #124

**Pull request closed without merging**
