### PR TITLE
Digest and public post refresh

### PR DESCRIPTION
**Pull request by bago2k4**
Cards:
- https://trello.com/c/ayWsPsx3
- https://trello.com/c/ayWsPsx3

To test:
- get the public url of a post with comments, reactions and attachments
- [x] do you see headline?
- [x] do you see abstract?
- [x] do you see body?
- [x] do you see attachments?
- [x] do you NOT see comments?
- [x] do you NOT see reactions?
- [x] do you NOT see any mentions about your previous user?
- [x] does it respect design?
- now get the same link for digest (with `id=your-id-token`)
- [x] do you see headline?
- [x] do you see abstract?
- [x] do you see body?
- [x] do you see attachments?
- [x] do you see comments?
- [x] do you see reactions?
- [x] do you see a button to login as your user at the top with avatar?
- [x] can you comment?
- [x] can you react?
- [x] does it respect design?

NB: i accidentally merged `why-it-matters` into this branch to update it, but before i had merged this branch into that. So i guess now the only way is to review them together: https://github.com/open-company/open-company-web/pull/853

### CODE REVIEW

**Comment by bago2k4** [comment]
[Post view for digest links (with hidden credentials)](https://trello.com/c/ayWsPsx3/2012-post-view-for-digest-links-with-hidden-credentials)

**Comment by bago2k4** [comment]
[Post view for public posts](https://trello.com/c/ynuis0c4/2013-post-view-for-public-posts)

**Comment by belucid** [comment]
@bago2k4 when using digest link the comment box should have my avatar, not generic: https://take.ms/hjwYH

**Comment by bago2k4** [comment]
Do you see you avatar in the top right corner @belucid ?

**Comment by belucid** [comment]
I do @bago2k4, it's only the generic one at the bottom in the new comment field.

**Comment by bago2k4** [comment]
@belucid i fixed it on client side. If the user is on the secure activity route and has no JWT but has an id-token present i get the user infos from there.
Not sure if a auth side fix was better, returning at least the GET user link when the auth-settings are requested with the id-token.
WYT?
I was more afraid of breaking other things with the service side change though so i opted for the client solution.

**Comment by belucid** [comment]
Ready, waiting for #853 though.

**Comment by belucid** [comment]
@bago2k4 please resolve the conflicts here.

**Pull request merged**
