### PR TITLE
Minor ui punchlist

### PR DESCRIPTION
**Pull request by bago2k4**
the light box vertical placement was fixed with some css media queries on the screen size:
- from 0 up to 768 px it's 30px
- from 769 up to 1300 px it's 130px
- from 1301 to the moon it's 230px

### CODE REVIEW

**Comment by bago2k4** [comment]
[Minor UI punch list](https://trello.com/c/XEkaKlXj/675-minor-ui-punch-list)

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@bago2k4 

- [ ] Can't load pricing or about pages, get error: 

```
derivatives.js:182 Uncaught Error: Assert failed: No get! derivative function found in component context
get-drv!
```

The rest looks good.

**Comment by belucid** [comment]
@bago2k4 

- [ ] New issue. Looking at a read-only company. It has "Company Settings" in the drawer. It shouldn't.

**Comment by belucid** [comment]
@bago2k4 

- [ ] Suggestion from @stulev last week. Move invite above the list: http://take.ms/d0GpX

**Comment by bago2k4** [comment]
@belucid this is good to go

**Comment by belucid** [comment]
Reviewing.

**Pull request merged**
