### PR TITLE
UX desktop: invite Slack button

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/jcgS60zf
Abstract: https://share.goabstract.com/58526e22-02dc-43dd-aa53-4ff041793aa8

To test:
- signup via email
- go to invite team
- [x] do you see a button to add Slack? Good
- [x] design is ok? Good
- click the button
- [x] are you redirected to Slack auth first step (small set of permissions)? Good
- now go to invite again
- [x] do you still see the same button? Good
- click it again
- [x] are you redirected to Slack auth *second* step (extended set of permissions)? Good
- now go back to invite
- [x] do you have invite via Slack now? Good

### CODE REVIEW

**Comment by bago2k4** [comment]
[UX desktop: invite Slack button](https://trello.com/c/jcgS60zf/1871-ux-desktop-invite-slack-button)

**Comment by bago2k4** [comment]
@belucid possible issue with this: if you have already a team associated we should change the copy of the green button from: `add a Slack team` to `Enable the Carrot Bot for Slack` but that doesn't fit on that line.
If you have a better copy to suggest i'll fix it on the fly when you get here, or we can go with the same copy in both cases.

**Comment by belucid** [comment]
@bago2k4 "Enable Carrot Bot" is fine

**Comment by bago2k4** [comment]
@belucid copy updated

**Pull request merged**
