### PR TITLE
New mobile edit

### PR DESCRIPTION
**Pull request by bago2k4**
Design: https://share.goabstract.com/49727312-7531-438a-85ad-26aebaac8e65

To test on mobile:
- tap new post
- save draft
- edit draft
- publish
- edit published post
- save

To test on desktop repeat the steps above

### CODE REVIEW

**Comment by bago2k4** [comment]
@thepug @belucid i marked this as URGENT since i need this mobile post layout for the mobile NUX.

**Comment by belucid** [comment]
@bago2k4 

If you go to the title and enter a char and delete it, then you can post w/ no headline.

-or-

If you put only whitespace (such as a single space) in the headline, you can post w/ no headline

Seems we won't headline to pass `blank?` test.

**Comment by belucid** [comment]
@bago2k4 

Sequence:

- Create a post, save it as a draft
- Edit the draft, and post it
- Edit the result post, notice it still says "Draft for:" in the blue bar.

Oh, then I realized it's just always that way on mobile for any post. Even if you edit a post that's been there for days.

**Comment by belucid** [comment]
@bago2k4 

On desktop, when you click New Post, the headline and body start very close together, and then when you type the first character into the headline, the body jumps down.

**Comment by belucid** [comment]
@bago2k4 Code looks good. Just those 3 QA items.

**Comment by belucid** [comment]
@bago2k4 "dirty" state doesn't seem to be clearing out on save.

Sequence:

- Edit a post
- Change the board
- Save
- Hit the X, warns you about losing changes

- Edit a post
- Change the content
- Save
- Hit the X, warns you about losing changes

**Comment by belucid** [comment]
@bago2k4 If the FF cursor to high at new post open is quick, let's do it, if not we'll defer it.

We decided the headline placeholder should remain even if the field is focused if the field has no value.

**Comment by bago2k4** [comment]
@belucid (@thepug ) the placeholder is there now for FF, Safari and Chrome when you enter the view. When you start typing it goes away. If you delete all the content the placeholder comes back only in Chrome, the other 2 browsers leave an invisible <br> in the field that makes it harder to know it's empty with simple CSS.

**Comment by thepug** [comment]
> @belucid (@thepug ) the placeholder is there now for FF, Safari and Chrome when you enter the view. When you start typing it goes away. If you delete all the content the placeholder comes back only in Chrome, the other 2 browsers leave an invisible 
in the field that makes it harder to know it's empty with simple CSS.

Should we use javascript here to test for empty?  Why won't this work https://github.com/open-company/open-company-web/pull/363/commits/cc15da489ef18e9ac799107874c8d363fcdf5c5f#diff-c257f209ba0537d00a3b216f0e4d992aL429

**Pull request merged**
