### PR TITLE
Share snapshot revised flow

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/6gqbWKiL

This also contains the `archived-topics` branch and its PR #144 was closed in favor of this

### CODE REVIEW

**Comment by belucid** [comment]
@bago2k4 

The PATCH of `:stakeholder-update` in company needs to come when the user clicking "PREVIEW AND SHARE". Otherwise the selections they make aren't previewed. To see this, go to Buffer, click "SHARE SNAPSHOT" and unselect one or more of the topics, then click "PREVIEW AND SHARE", notice the topics are still there in your preview.

**Comment by belucid** [comment]
@bago2k4 https://app.getsentry.com/opencompany/oc-staging-web/issues/131047625/

**Comment by belucid** [comment]
@bago2k4 

- [ ] The color of the grey bar isn't the same for snapshot selection and preview, #989EA6  vs. #A7ADB5 
- [ ] The height of the grey bar isn't the same for snapshot selection and preview

**Comment by belucid** [comment]
@bago2k4 

-[ ] company with blank `:stakeholder-update` -> `:title` is shown with a blank title rather than an auto-generated title.

**Comment by bago2k4** [comment]
@belucid about:
> First edit works fine, but when you make the 2nd edit (no refresh in between) you just get the spinner on the POST button w/ no network request made and no console error.
I tested this flow: from dashboard, start with "share a snapshot", select some topics, click "preview and share", edit title, "share url", copy url, done (close dialog), edit snapshot title, click "share url" copy url, done (close dialog).
I don't get the infinite spinner, can you be more accurate describing the flow?

**Comment by belucid** [comment]
@bago2k4 use the grey bar height from the "share" screen as the height on the "preview" screen. The grey bar should bisect the company logo half-way.

**Comment by belucid** [comment]
@bago2k4 this: "First edit works fine, but when you make the 2nd edit (no refresh in between) you just get the spinner on the POST button w/ no network request made and no console error.” is just about regular topic editing. Nothing with the snapshots.

**Comment by belucid** [comment]
@bago2k4 

-[ ] The font (at least on desktop) of the times in the menu drawer doesn't match Zeplin.

**Comment by belucid** [comment]
@bago2k4 

- [ ] Signing out on `mainline` works fine. Signing out on this branch doesn't signout.

**Comment by bago2k4** [comment]
@belucid logout probably didn't work because local_settings before had `(def jwt-cookie-domain "localhost")`  instead of `(def jwt-cookie-domain "127.0.0.1")` and to remove a cookie i have to specify the domain (not sure why but if i don't goog.net.cookies doesn't work).
I think you have the jwt cookie saved under localhost and now you try to remove it for 127.0.0.1, i changed local_settings back to localhost. any particular reason why you used 127.0.0.1 instead of localhost?

**Comment by belucid** [comment]
@bago2k4 I'll retest the logout. You're probably right.

**Comment by belucid** [comment]
- [ ] https://github.com/open-company/open-company-web/issues/131
- [ ] https://github.com/open-company/open-company-web/issues/130

**Comment by belucid** [comment]
@bago2k4 signout is OK.

**Comment by belucid** [comment]
@bago2k4 
- [ ] https://app.getsentry.com/opencompany/oc-production-web/issues/131487153/

**Comment by belucid** [comment]
@bago2k4 please merge mainline.

**Comment by belucid** [comment]
- [ ] Sequence: expand a content topic, edit the body, click post, click the pencil, try to edit the body again, notice you can't get the body to be editable.

**Comment by bago2k4** [comment]
@belucid this is ready

**Comment by belucid** [comment]
:+1: :boom:

**Pull request merged**
