### PR TITLE
Fixed the regex for the email and domain validation in the html forms.

### LINKED ISSUE #846: Email format validator has false negatives on funky domain extensions
My email address was reported as incorrect because it finishes by `.taipei`.

`.tw` works, so I guess that there is a whitelist somewhere that may need an update - or maybe there shouldn't be a whitelist.

I spotted the problem in 2 places:

email-format-problem

image

However, the validation problem did not prevent me from progressing through the registrations.

### PR DESCRIPTION
**Pull request by green-coder**
Not ready to be merged yet, I still need to test it.

Fixes #846

### CODE REVIEW

**Comment by bago2k4** [comment]
@green-coder no rush, just remember to pull latest mainline in before requesting review. It has conflicts

**Comment by green-coder** [comment]
I was able to run the `auth`, `storage`, `interaction` and  `web` services, and I tested the email matching on the account registration page. It seems to work fine.

I did not find yet how to register a user on my instance, so I did not test the page which tests only the domain part of the email. But I expect it to work as the code is very similar to the one I tested above.

**Comment by bago2k4** [comment]
Hi vincent, thanks, don't worry about registration. This should be enough.
I'll take a look very soon. Sorry for the late reply but i have been out
since yesterday and I'm still on mobile today.

**Comment by bago2k4** [comment]
This looks good @green-coder , merging in.
Thanks

**Pull request merged**
