### PR TITLE
Big web 2

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/oDEwnhLB/354-big-web-round-2

To test follow the checklist in the card and verify that the lightbox is working as expected.

### CODE REVIEW

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@bago2k4 shouldn't be able to edit a prior revision. As soon as user clicks Previous and is not viewing latest section, remove the edit pencil.

**Comment by belucid** [comment]
@bago2k4 partial scroll bar shown for Buffer finance content expanded: http://take.ms/qwtUK

**Comment by belucid** [comment]
@bago2k4 unused scroll bar is visible, shouldn't be:

http://take.ms/yKXsh

http://take.ms/i2drM

**Comment by belucid** [comment]
@bago2k4 when opening a topic to a light box, the dashboard (topic cards and category nav) shifts to the right, then when closing it shifts back to the left.

**Comment by belucid** [comment]
@bago2k4 Doesn't look like this one was implemented: "For very short windows < 670 pixels high, constrain lightbox height so top and bottom have 10px gap."

http://take.ms/xswuL

**Comment by belucid** [comment]
@bago2k4 missing gap between headline and body: http://take.ms/uYgIr

**Comment by belucid** [comment]
@bago2k4 Font weight 600 (semi-bold in theory) just seems to be bolding it. Pragmatically use font weight 500 for headline text (it's too bold right now at 600) or look into pulling in a Proxima semibold font face so we get an accurate semi-bold.

**Comment by bago2k4** [comment]
@belucid all done.

___

about this: 
> when opening a topic to a light box, the dashboard (topic cards and category nav) shifts to the right, then when closing it shifts back to the left.

I'm unable to see the shift, can you add a screen capture or something?

___

About this:
> unused scroll bar is visible, shouldn't be:

i think that's visible only to you, i remember you saying that you changed some settings and you have always the scroll bar containers visible, can be? i don't see them at all, also while i'm scrolling i see only the scrollbar and i think this is the normal behaviour for all users.

**Comment by belucid** [comment]
@bago2k4 here is a video of the shift right and left when opening topics and closing topics:

http://take.ms/8mQf6

**Comment by belucid** [comment]
@bago2k4 This one isn't addressed: "Font weight 600 (semi-bold in theory) just seems to be bolding it. Impact of this is headline is too bold. Pragmatically use font weight 500 for headline text (it's too bold right now at 600) or look into pulling in a Proxima semibold font face so we get an accurate semi-bold."

**Comment by belucid** [comment]
@bago2k4 content is bigger than window now:

http://take.ms/2ZYnv

http://take.ms/jjdPL

**Comment by belucid** [comment]
@bago2k4 This one isn't addressed: "unused scroll bar is visible, shouldn't be"

**Comment by belucid** [comment]
@bago2k4 headline is repeated now on mobile web when you expand a topic

**Comment by belucid** [comment]
@bago2k4 Looking at Buffer now on mobile, the company description “A better way to …” isn’t no longer aligned with company name

**Comment by belucid** [comment]
@bago2k4 some new mobile regressions with the category nav:

* It does this funky thing where the Category bar turns into a grey bar while being scrolled until scrolling stops, and then when scrolling back it creates a strange interaction with the logo that scrolls behind it. 
* If I choose another category while company name / category nav. is scrolled all the way to the top it “jumps” when you pick the new category.
* when playing with it for a bit, you end up with this: http://take.ms/xzbOi

**Comment by belucid** [comment]
@bago2k4 Make the company header background full white (rather than transparency color it is now), because we’ll have company logos on white that won’t look right otherwise (right now it’s transparent, and so it picks up grey from the container). Also remove the top border above category nav. so we look like this: http://take.ms/uVePE

**Comment by belucid** [comment]
@bago2k4 On Buffer, Nav. from ALL to COMPANY, and the company topics are taller. Then nav. To FINANCIAL and back to COMPANY, and now the company topics are shorter. They should have been shorter with the first navigation.

**Comment by bago2k4** [comment]
@belucid 

> here is a video of the shift right and left when opening topics and closing topics:

I'm still unable of reproduce this and it's very hard to fix it without repeating. Can you give me more info: are you on chrome? what size is your window? you sure you recompiled the scss files with the latest changes?

___

> This one isn't addressed: "unused scroll bar is visible, shouldn't be"

Please read my last comment above this, there i suggested a possible explanation

___

> This one isn't addressed: "Font weight 600 (semi-bold in theory) just seems to be bolding it. Impact of this is headline is too bold. Pragmatically use font weight 500 for headline text (it's too bold right now at 600) or look into pulling in a Proxima semibold font face so we get an accurate semi-bold."

I did address this: i pulled in Proxima Nova Semibold, the way to use semibold is to add the semibold font to your typekit and then setting the font-weight to 600 instead of changing the font family. that's what i did and now is a little less bold than before but still not enought light i guess. i'll try setting to 500 (maybe too light though)

___

> Looking at Buffer now on mobile, the company description “A better way to …” isn’t no longer aligned with company name

I did that on purpose following the _Default_ mock in Zepling, the one before (_Dashboard - Company_) show them aligned to the left but the one after where the view is scrolled (_Scrolled_) shows that the company name is more indented than the first category of the navbar (following the _Default_ mock). which one is the good one?

___

About mobile regressions:
> It does this funky thing where the Category bar turns into a grey bar while being scrolled until scrolling stops, and then when scrolling back it creates a strange interaction with the logo that scrolls behind it.

I'm unable to replicate this too, do you see this on Chrome with the device mode on or on your real device? if the latter, which device, Android or iOS?

> If I choose another category while company name / category nav. is scrolled all the way to the top it “jumps” when you pick the new category.

This is strictly connected to an item in [this](https://trello.com/c/G7WJ5sDu) card checklist (Mobile Checklist), fixing the last item will fix this too.

> when playing with it for a bit, you end up with this: http://take.ms/xzbOi

I added this to the Mobile Checklist too, let me know if that's ok for you. I'll do those fix after the editing cards since you said it's more urgent.

**Comment by bago2k4** [comment]
@belucid just to keep track: all addressed or postponed as discussed in Slack. Ready again

**Pull request merged**
