### PR TITLE
Growth finances redlines

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/PwrKjkHC

To test follow the card and the mocks.
Double check values for cash flow and runway. Before runway was calculated using the avg burn rate of the last 3 months, in here the runway is of the current month.

Charts have no animation for the moment.

NB: some new components don't have tests yet, i'll write some in this branch if i have the time but i think we can start to collect feedbacks here just the same.

### CODE REVIEW

**Comment by bago2k4** [comment]
@belucid you cans tart reviewing, i'll fix the tests ASAP

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@bago2k4 Intent was not to show the 3rd bar (cashflow) at all, only include it as data above the chart.

**Comment by belucid** [comment]
@bago2k4 having the chart data move around as you hover over months and select them feels bad. Let's just center the data above the chart and leave it there.

**Comment by belucid** [comment]
Put some more white space between the data item labels: Revenue, Costs, Cashflow

**Comment by belucid** [comment]
@bago2k4 we use the shortened time period label (yrs, mnths, wks) on the collapsed topic, because space is at a premium, but in the expanded topic, let's use the full word.

**Comment by belucid** [comment]
@bago2k4 May on Buffer says 1 yrs. We need logic so we never say 1 with plural. So: 1 day, 1 month, 1 week, 1 year. Never 1 day, 1 months, 1 weeks, 1 years.

**Comment by belucid** [comment]
@bago2k4 Buffer's key metric of total registered users is going up each month, but the line chart is going down each month.

**Comment by belucid** [comment]
@bago2k4 on hovering over a data point in the Growth line chart, the data point gets bigger, but the line is still visible over the right half of the data point.

**Comment by belucid** [comment]
@bago2k4 clicking the previous link causes the edit topic to be shown.

**Comment by belucid** [comment]
@bago2k4 the pillbox outline for finance seems darker than the mock. The right and left padding of the word in the pillbox seems smaller than the mocks.

**Comment by belucid** [comment]
@bago2k4 Headline isn't formatted properly for finances: http://take.ms/03AGd

**Comment by belucid** [comment]
@bago2k4 no runway shown on collapsed card for New.ly. Card doesn't expand for New.ly.

**Comment by belucid** [comment]
@bago2k4 Buffer's runway seems opposite. Sep and Oct. were not profitable, so they should have a runway. May-Aug were profitable, so the Runway should show profitable.

**Comment by bago2k4** [comment]
@belucid ready again

**Comment by belucid** [comment]
@bago2k4 let's use wide area hover targets to cut down on the jumpiness http://take.ms/arVTu

**Comment by belucid** [comment]
@bago2k4 the x-axis labels for finance should all be light green except the active month (the one that's got data showing above the chart (either by selection or hover)) which should be darker green.

The x-axis label for growth should all be light blue except the active period (the one that's got data showing above the chart (either by selection or hover)) which should be darker blue.

**Comment by belucid** [comment]
@bago2k4 Clicking a particular pillbox in the collapsed Growth card when expanding should make that metric active at the start when the card expands.

**Comment by belucid** [comment]
@bago2k4 Headline is cut off on finances collapsed section: http://take.ms/tpfQW

To see this, pull mainline of api and re-import ent.edn.

**Comment by belucid** [comment]
@bago2k4 Odd bug:

Go to Enterprise Inc., expand finances.

Click the previous link twice in rapid succession. You end up here: http://take.ms/18n7l

**Comment by belucid** [comment]
@bago2k4 Seems the text isn't quite vertically centered in these pillboxes, it's too high: http://take.ms/FIIZO

**Comment by belucid** [comment]
@bago2k4 on mobile, finance chart isn't showing currency symbol for cash or cash flow in expanded section: http://take.ms/QyLMl

**Comment by belucid** [comment]
@bago2k4 On mobile there is not enough room for 3 across data for cashflow. Let's stack them vertically instead: http://take.ms/L4ECD

**Comment by bago2k4** [comment]
@belucid if travis is still happy after this last 2 commits this is ready again

**Comment by belucid** [comment]
@bago2k4 clicking "< Previous" only works once and results in: ```Uncaught TypeError: Cannot set property 'disabled' of null``` (this is from Buffer finances)

**Comment by belucid** [comment]
@bago2k4 not sure that we have any guidelines in the mocks/Zeplin, but presumably we need some bottom margin here: http://take.ms/rBnMj

**Comment by belucid** [comment]
@bago2k4 this feels slightly cramped. A few more pixels between the data and headline would be good: http://take.ms/sPUcT

**Comment by belucid** [comment]
@bago2k4 go to Mobile -> ent-inc -> Finances -> Expanded -> Cash flow

Tap each month right to left, Aug to May, then left to right, May to Sept.

Notice:

* Tapping AUG selects JUL
* Tapping JUL brings the data down into the chart area (right to left)
* Tapping AUG selects JUL and brings the data down into the chart area (left to right)
* Tapping SEP selects AUG (left to right)

**Comment by belucid** [comment]
@bago2k4 On mobile Finances, X-axis labels are a little cramped. Let's get 1 character back by showing year as '15 rather than 2015. On big web leave it as 2015.

**Comment by bago2k4** [comment]
@belucid and ready again again

**Comment by belucid** [comment]
@bago2k4 I still can't click Previous more than once on Buffer's Finance.

**Comment by belucid** [comment]
@bago2k4 X-axis still seems too cramped on mobile when we have 6 months of data (see Buffer):

**Comment by belucid** [comment]
@bago2k4 I'm seeing the old Edit Topic button on mobile. No mobile editing anymore:

http://take.ms/YJ0h0

**Comment by bago2k4** [comment]
@belucid ready again again again

**Comment by belucid** [comment]
@bago2k4 Glorious!

**Pull request merged**
