### PR TITLE
UX desktop: reminder notifications click

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/R2Dmpg1n

To test:
- with user B set a reminder for user A
- [x] did you get an in-app notification with user A? Good
- click it
- [x] did it open reminders? Good
- now change the reminder via REPL so it's trigged in the next minute
- wait for the notification
- [ ] did you get it? Good
- click it
- [ ] did it open Cmail? Good

### CODE REVIEW

**Comment by bago2k4** [comment]
[UX design: reminder click](https://trello.com/c/R2Dmpg1n/1876-ux-design-reminder-click)

**Comment by belucid** [comment]
@bago2k4 the 2nd part of the test didn't work.

I did get the notification in the system notification (bottom left). Clicking it did nothing though. And I never saw a notification for it in the bell dropdown (is that the intent? I assume those notifications should be shown in the bell too).

**Comment by belucid** [comment]
Get this in the console @bago2k4 

```
raven.inc.js:58 Warning: Encountered two children with the same key, `user-notification-2019-01-22T14:00:00.000Z`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in div (created by user-notifications)
    in div (created by user-notifications)
    in div (created by user-notifications)
    in user-notifications (created by navbar)
    in div (created by navbar)
    in div (created by navbar)
    in div (created by navbar)
    in div (created by navbar)
    in nav (created by navbar)
    in navbar (created by org-dashboard)
    in div (created by org-dashboard)
    in div (created by org-dashboard)
    in org-dashboard (created by app)
    in app
```

**Comment by belucid** [comment]
Same result @bago2k4 after ensuring that hot reload isn't involved. 2 key error happens on FF if that's relevant.

**Comment by belucid** [comment]
@bago2k4 

`Warning: Encountered two children with the same key, user-notification-2019-01-22T14:00:00.000Z-. Keys should be unique so that components maintain their identity`

**Comment by belucid** [comment]
@bago2k4 FWIW the grey X in the top right of the notification (as opposed to the OK link) doesn't actually seem to do anything.

**Pull request merged**
