### PR TITLE
New Search Design

### PR DESCRIPTION
**Pull request by thepug**
Changes the search UI to fit the new design work.

Depends on https://github.com/open-company/open-company-search/pull/7

### CODE REVIEW

**Comment by thepug** [comment]
[New search design](https://trello.com/c/xkwx1Dcc/1148-new-search-design)

**Comment by belucid** [comment]
Type in a few search characters, then backspace over your search until it's cleared, you end up with a search of `<br>` (and a lot of spurious matches.

`18-01-15 10:23:37 Seans-Mac-Pro.local DEBUG [oc.search.elastic-search:189] - Executing Query: {:bool {:filter {:bool {:should [{:term {:org-team-id.keyword "5d69-42ec-8179"}}], :must [{:term {:org-uuid.keyword "3958-4a89-93f7"}} {:term {:type.keyword "entry"}}]}}, :should [{:match {:slug "<br>"}} {:match {:name "<br>"}} {:match {:author-name "<br>"}} {:match {:headline "<br>"}} {:match {:body "<br>"}}]}}`

Once you've picked up this `<br>` in your search, typing chars again results in a search with `<br>` in it too.

Beyond just fixing the UI, there's a not in search service about not indexing HTML.

**Comment by belucid** [comment]
@thepug 

After clicking the X, I'm left with a grey square where it was (browser is FF): http://take.ms/u6iRC

**Comment by belucid** [comment]
@thepug some differences from design:

http://take.ms/iqvIv

- Design has the X and search field vertically aligned
- Design has a blue cursor

**Comment by belucid** [comment]
@thepug 

With search results showing, nav. to another board. You are left with search results "stuck" there. They should go away.

**Comment by belucid** [comment]
@thepug clicking the X ought to clear the search as well as close the search UI

**Comment by belucid** [comment]
Some feedback on call about hover color and dropdown placement.

**Comment by thepug** [comment]
All items above addressed @belucid.  You can see them on staging.

**Comment by thepug** [comment]
addressing feed back in the qa doc

https://docs.google.com/document/d/1X3j869Y8n94zfqaGVhrWf8VOlr3qEa_4a1fxtIjH6fs/edit#

**Comment by belucid** [comment]
@thepug this ready for review again?

**Comment by thepug** [comment]
> @thepug this ready for review again?

I wasn't sure what to do about stuart's feedback.

**Comment by belucid** [comment]
Reviewing again.

**Comment by belucid** [comment]
@thepug 

- [ ] SEARCH RESULT header font doesn't match, impl. has med. but design has heavy.
- [ ] White space under final search result doesn't seem right to me, seems we should either match it to the white space above SEARCH RESULT or ask Ryan. All the designs I see have a show more down there so we don't have a design w/ a final result at the bottom.

**Comment by belucid** [comment]
@thepug 

- [ ] shouldn't get the search UI if user is not a member of the company (or is totally anonymous), but is just accessing public boards

**Pull request merged**
