### PR TITLE
Dark mode

### PR DESCRIPTION
**Pull request by bago2k4**
Card: https://trello.com/c/wRV1c4fd

To test:
- check all views in light mode
- check all views in dark mode
- check Carrot inherit the dark mode from system when in auto
- check that you can override the system mode from the setting panel
- check that you can go back to auto mode from the setting panel

### CODE REVIEW

**Comment by belucid** [comment]
@bago2k4 the dropdown lists in notifications in dark mode (on FF, maybe others) are broken. Only the highlighted option is visible. The others are white on white text.

**Comment by bago2k4** [comment]
@belucid fixed

**Comment by belucid** [comment]
@bago2k4 

Merge conflicts here. Also vertically center "Auto" and add "Use system preference" tooltip.

**Comment by belucid** [comment]
@bago2k4 invite panel is still white in dark mode

**Comment by belucid** [comment]
@bago2k4 invite people link doesn't get a new color in dark mode and so is too dark: https://monosnap.com/direct/L5pYGQReWzDI2uG8rmFvFMobNZYLLz

**Comment by belucid** [comment]
@bago2k4 the comment action menu is still light in dark mode

**Comment by belucid** [comment]
@bago2k4 create section and section settings panel are light in dark mode.

**Comment by belucid** [comment]
@bago2k4 the private/public section icons are dark in dark mode, not visible.

**Comment by belucid** [comment]
@bago2k4 the complete follow-up icon is missing in dark mode.

**Comment by belucid** [comment]
@bago2k4 the share dialog is light in dark mode.

**Comment by belucid** [comment]
@bago2k4 the move dialog is light in dark mode.

**Comment by belucid** [comment]
> @bago2k4 the comment action menu is still light in dark mode https://monosnap.com/direct/wgll7SYPhaYkS3LWkWM1AUVDohDhXc

I still see this one. Is this the intended design in dark mode?

**Comment by bago2k4** [comment]
> > @bago2k4 the comment action menu is still light in dark mode https://monosnap.com/direct/wgll7SYPhaYkS3LWkWM1AUVDohDhXc
> 
> I still see this one. Is this the intended design in dark mode?

This is dark in light mode, so it's light in dark mode :)

**Comment by bago2k4** [comment]
@belucid addressed all your commetns

**Pull request merged**
