### PR TITLE
Ui punchlist

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/4AVJR5tO

### CODE REVIEW

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@bago2k4 

- [ ] Footer handling during drawer expansion looks pretty good on a "short" company like `/new` but is borked on a "long" company like `/buffer` or `/front-office-collections-etc`. Both the animation and the end result has some issues https://monosnap.com/file/uRph9oFdmTADJbzpiaPV0lm9X6DUt2.png
- [ ] when loading a share URL such as `https://staging.opencompany.com/buffer/updates/june-2016-update-1e95d` you see the spinner, then the footer at the top, then the update. Shouldn't see the footer alone at the top.
- [ ] On a newly added topic, if you click into snippet, everything is fine, cursor is there and snippet text is there and they line up. If you tab into snippet from headline though, the placeholder text moves down. Shouldn't.
- [ ] Clicking expand view button from FoCE should result in headline being focused, instead body is focused.
- [ ] Text should be lined up with text in a bullet that wraps to multiple lines (instead it wraps under the bullet) https://monosnap.com/file/Hfp767uQH6clsVOlXNQ58XYk5kwATQ.png

**Comment by bago2k4** [comment]
@belucid ready again, sorry but i saw your feedback only yesterday night. The problem with the menu drawer i couldn't replicate so i tried fixing it. let me know if you still see it.

**Comment by belucid** [comment]
- [ ] snippet placeholder text no longer goes away on typing

**Comment by belucid** [comment]
- [ ] footer issue still present, scrolls up on activation

**Pull request merged**
