### PR TITLE
Stream view

### PR DESCRIPTION
**Pull request by bago2k4**
Abstract link: https://share.goabstract.com/ccfe1bc2-3ab1-48b9-aef2-0d7589d7c55a

### CODE REVIEW

**Comment by thepug** [comment]
This might be the emoji picker issue.  I tried to choose an emoji and got this error and it happens often.
```
raven.inc.js:390 Uncaught Error: No protocol method IAssociative.-assoc defined for type string: bb07-4687-9fed
    at Object.cljs$core$missing_protocol [as missing_protocol] (core.cljs:304)
    at Object.cljs$core$_assoc [as _assoc] (core.cljs:613)
    at Function.cljs.core.assoc.cljs$core$IFn$_invoke$arity$3 (core.cljs:1954)
    at cljs$core$assoc (core.cljs:1947)
    at oc$web$actions$handle_reaction_to_entry (actions.cljs?rel=1519052563178:676)
    at actions.cljs?rel=1519052563178:1312
    at cljs.core.MultiFn.cljs$core$IFn$_invoke$arity$2 (core.cljs:10539)
    at core.cljs:4437
    at Function.cljs.core.swap_BANG_.cljs$core$IFn$_invoke$arity$3 (core.cljs:4437)
    at cljs$core$swap_BANG_ (core.cljs:4426)
    at dispatcher.cljs?rel=1519052555639:304
    at cljs_flux.dispatcher.Dispatcher.cljs_flux$dispatcher$IDispatcher$_invoke_callback$arity$2 (dispatcher.cljs?rel=1519052552434:31)
    at cljs_flux.dispatcher.Dispatcher.cljs_flux$dispatcher$IDispatcher$dispatch$arity$2 (dispatcher.cljs?rel=1519052552434:61)
    at cljs_flux$dispatcher$dispatch (dispatcher.cljs?rel=1519052552434:13)
    at oc$web$dispatcher$dispatch_BANG_ (dispatcher.cljs?rel=1519052555639:307)
    at Object.onClick (reactions.cljs?rel=1519052558362:147)
    at Picker.handleEmojiClick (picker.js:272)
    at _handleClick (emoji.js:58)
    at onClick (emoji.js:151)
    at HTMLUnknownElement.wrapped (raven.inc.js:386)
    at Object.ReactErrorUtils.invokeGuardedCallback (react-dom.inc.js:9017)
    at executeDispatch (react-dom.inc.js:3006)
    at Object.executeDispatchesInOrder (react-dom.inc.js:3029)
    at executeDispatchesAndRelease (react-dom.inc.js:2431)
    at executeDispatchesAndReleaseTopLevel (react-dom.inc.js:2442)
    at Array.forEach (<anonymous>)
    at forEachAccumulated (react-dom.inc.js:15423)
    at Object.processEventQueue (react-dom.inc.js:2645)
    at runEventQueueInBatch (react-dom.inc.js:9041)
    at Object.handleTopLevel [as _handleTopLevel] (react-dom.inc.js:9052)
    at handleTopLevelImpl (react-dom.inc.js:9129)
    at ReactDefaultBatchingStrategyTransaction.perform (react-dom.inc.js:14724)
    at Object.batchedUpdates (react-dom.inc.js:8805)
    at Object.batchedUpdates (react-dom.inc.js:12852)
    at dispatchEvent (react-dom.inc.js:9204)
    at HTMLDocument.wrapped (raven.inc.js:386)```

**Comment by bago2k4** [comment]
@thepug solved that and i made some step forward on the performance issue, let me know WYT

**Comment by bago2k4** [comment]
@thepug the emoji issue is fixed and also the performance should be better now.
I suggested changing to 10 the number of posts storage send, that should be on mainline too.

**Comment by thepug** [comment]
Are the reactions suppose to do this on mobile? 

screenshot

**Comment by bago2k4** [comment]
@thepug well they shouldn't of course but those are the UI pieces we have right now, since the reactions are to be changed soon i think we can leave this as is for now. WYT?

**Comment by thepug** [comment]
> @thepug well they shouldn't of course but those are the UI pieces we have right now, since the reactions are to be changed soon i think we can leave this as is for now. WYT?

I think @belucid and @stulev might want this fixed before releasing.

**Comment by thepug** [comment]
screenshot

I get this gradient when the comments are scrolled to the bottom. Was this supposed to be fixed?

**Comment by thepug** [comment]
If there is one board you never see the All Posts view.  Not sure if we want this behavior considering All Posts is now a different view.

screenshot

**Comment by thepug** [comment]
Is it fine that attachments are in the middle or should they always be near the reactions?

screenshot

**Pull request merged**
