### PR TITLE
Data topic editing

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/hxVPPU6v

To test Finances:
- edit cash
- edit costs
- edit revenue
- save the new data
- mix the previous actions
- check that the chart always respect the latest data inserted

To test growth:
- try to edit the data of an existing metric
- try to edit the metadata of an existing metric
- try to add a new metric
- update the new inserted metric after it was saved
- try to remove a metric

### CODE REVIEW

**Comment by belucid** [comment]
Reviewing

**Comment by belucid** [comment]
Finance Items

- [ ] Make the headline have the initial focus, not the notes
- [ ] Initially show just 6 months until they click "More..." rather than 12
- [ ] Show the runway as blank, rather than "break-even" when there is no data
- [ ] Align headline counter w/ headline, only show when headline has focus
- [ ] Reduce headline length (only for finance and growth) to 80

**Comment by belucid** [comment]
@bago2k4 we'll certainly need another iteration round, but the above checklist is complete for now.

**Comment by bago2k4** [comment]
@belucid here is how you add a new metric: https://www.evernote.com/shard/s29/sh/88a3dcdb-6535-4339-8559-197a521ef609/dfec0ed29ee40cfe4524c2e2701e9860

since you didn't see it we probably need to highlight it, a green background for only that pillbox?

**Comment by bago2k4** [comment]
@belucid only this one is left:
> Had no headline (New.ly), added a headline, clicked Save, brought back to the expanded topic, there's no headline. Edit again. Just click cancel, back at the expanded topic, headline is there.

as we discussed in slack we should create a new card in trello for this. that ok?

**Comment by belucid** [comment]
Reviewing again.

**Comment by belucid** [comment]
- [ ] Text on "+ New metric" as white
- [ ] Center metric entry http://take.ms/DvaqW
- [ ] Error sequence below


Sequence

**Comment by belucid** [comment]
@bago2k4 next round of feedback is in.

**Comment by bago2k4** [comment]
@belucid all done if travis is happy

**Pull request merged**
