### PR TITLE
Reopened

### PR DESCRIPTION
**Pull request by bago2k4**
card: https://trello.com/c/Cvo2aQ5t/578-ui-punch-2
@belucid i didn't see you had already merged this. i fixed one more issue:
> Having two primary buttons (gold) on the screen at once is confusing during add image link, seems broken. Instead put the text box/add/cancel below the divider line in the place of the char count/cancel/save. Have those hidden until the user clicks add or cancel.

The remaining 2 are:
> Adding a link in medium editor w/o protocol (http/https) makes it a relative link. If protocol is missing from what they provide, we should add "http://" to it.
- [x] 

I need to study a little bit more the events of the Anchor plugin of medium editor
> `:ten:` still present in emoji picker
- [x] 

I don't know why the image is missing but it's an internal problem of emojione-picker react component. same as before it needs some more time to find the problem source.

### CODE REVIEW

**Comment by belucid** [comment]
- [ ] cancel is on own line
- [ ] focus the text box on click

**Comment by belucid** [comment]
Reviewing.

**Comment by belucid** [comment]
@bago2k4 

Enter this as your URL:

```
upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Aerial_photo_Port_Stanley_edit.jpg/220px-Aerial_photo_Port_Stanley_edit.jpg
```

End up with a 400 from filestack (error code 152).

UI gets stuck at "100%" and there is no add / cancel for the image or save / cancel for the topic. You have to refresh the page.

We need to return the UI to normal once we get a response of any type from Filestack.

**Comment by belucid** [comment]
FWIW:

152	The remote URL couldn't be reached

**Comment by belucid** [comment]
Pause on this for now @bago2k4

**Comment by bago2k4** [comment]
Closing, merged in #185

**Pull request closed without merging**
